### ISSUE TITLE
Taille trop courte de certaines parties de l'interface

### ISSUE THREAD

**Issue by trebmuh** [pianobooster/PianoBooster#10]
Certaines parties de l'interface sont trop courte pour afficher tout le texte.

![pianobooster-bogue-1](https://user-images.githubusercontent.com/8705846/40140163-7478e2e0-5952-11e8-8129-1ff56f8f0a35.png)

_PS : c'était déjà le cas avec Qt4_

**Comment by captnfab** [comment]
Normalement, ce problème a été réglé.

**Comment by trebmuh** [comment]
La plupart ont été corrigées, merci @captnfab !

Il en reste une :

![pianobooster-1](https://user-images.githubusercontent.com/8705846/40370537-bff68eec-5de0-11e8-99da-a88c046e4f6d.png)

**Comment by captnfab** [comment]
Ok, ça ne le fait pas chez moi, ça doit dépendre de la taille de la police. Je me demande s'il n'y a pas un moyen d'éviter que ce problème soit dépendant de la config utilisateur.

**Comment by trebmuh** [comment]
Certainement.

De ce que j'en sais, il y a des logiciels dont l'IGU s'adapte en fonction du thème/police/config/... de l'utilisateur. De mémoire, il me semble me souvenir que Cadence (Qt5) fait ça.

**Comment by trebmuh** [comment]
@glixx why closing this thread? AFAIK, it's not fixed yet.
Please reopen.

**Comment by glixx** [comment]
@trebmuh will you write in English? I don't understand French. What to fix?
@captnfab is busy, I'm instead of him.

**Comment by trebmuh** [comment]
> @trebmuh will you write in English? I don't understand French. What to fix?

Well,... I find your tone a bit daddish here, please, step back.

1st: there are plenty of online translators
2nd: that's not because **you** don't understand something that you are fine with closing it
3rd: you didn't even took the time to write a message explaining why you're closing this message here

Thanks for showing a bit of consideration to other people and to refrain acting like that.

_And thanks for having reopening it here._

**Comment by glixx** [comment]
Online translators translated this topic about son of policeman. It did not have sense. Will you explane this bugreport in English? You will have more chances to fix it.

**Comment by glixx** [comment]
Should be fixed

**Comment by glixx** [comment]
![Снимок экрана от 2019-06-13 05-34-55](https://user-images.githubusercontent.com/2681872/59399537-07196f00-8d9d-11e9-8ece-77bbd6895fe6.png)
