### ISSUE TITLE
Wrong drawings with Qt5

### ISSUE THREAD

**Issue by trebmuh** [pianobooster/PianoBooster#11]
With Qt5:

![pianobooster-bogue-3](https://user-images.githubusercontent.com/8705846/40140220-a51963e8-5952-11e8-8286-2ca7609626c8.png)

With Qt4:

![pianobooster-bogue-3bis](https://user-images.githubusercontent.com/8705846/40140237-b15bcc5e-5952-11e8-9be1-e579ad78681e.png)

**Comment by admsasha** [comment]
fix patch

```
diff --git a/src/GlView.cpp b/src/GlView.cpp
index bcade88..58f9839 100644
--- a/src/GlView.cpp
+++ b/src/GlView.cpp
@@ -94,6 +94,7 @@ void CGLView::paintGL()
 
     if (m_forcefullRedraw) // clear the screen only if we are doing a full redraw
         glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
+    glPixelStorei(GL_UNPACK_ALIGNMENT,4);
     glLoadIdentity();
     //BENCHMARK(3, "glLoadIdentity"); 
```

**Comment by glixx** [comment]
Fixed by https://github.com/captnfab/PianoBooster/pull/30/commits/404a5bcb6a8447158737c7118067b15fc2cc15a1

**Comment by trebmuh** [comment]
Confirming that it works as expected with a rebuild from https://github.com/captnfab/PianoBooster/commit/b70ac96b8e0ac3d15d17c99a146f440415c3e024

Thanks @admsasha and @glixx .
