### ISSUE TITLE
Visual glitches with text sometimes

### ISSUE THREAD

**Issue by trebmuh** [pianobooster/PianoBooster#12]
With Qt5 :

![pianobooster-bogue-2](https://user-images.githubusercontent.com/8705846/40140320-ee5090c2-5952-11e8-9990-b1980920d6f1.png)

With Qt4 :

![pianobooster-bogue-2bis](https://user-images.githubusercontent.com/8705846/40140306-ea81d744-5952-11e8-8b89-dc7586fe9103.png)

**Comment by admsasha** [comment]
fix patch

```
diff --git a/src/GlView.cpp b/src/GlView.cpp
index bcade88..58f9839 100644
--- a/src/GlView.cpp
+++ b/src/GlView.cpp
@@ -94,6 +94,7 @@ void CGLView::paintGL()
 
     if (m_forcefullRedraw) // clear the screen only if we are doing a full redraw
         glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
+    glPixelStorei(GL_UNPACK_ALIGNMENT,4);
     glLoadIdentity();
     //BENCHMARK(3, "glLoadIdentity"); 
```

**Comment by glixx** [comment]
Fixed by https://github.com/captnfab/PianoBooster/pull/30/commits/404a5bcb6a8447158737c7118067b15fc2cc15a1

**Comment by glixx** [comment]
This bug was fixed already and can be closed.

**Comment by trebmuh** [comment]
Thanks @admsasha and @glixx .

It is much better now (build from https://github.com/captnfab/PianoBooster/commit/b70ac96b8e0ac3d15d17c99a146f440415c3e024) but there is still some issues (look at the R letter in "_Accuracy_", the "_r_" letter in Start, and the "_Bar_" word):

![pianobooster](https://user-images.githubusercontent.com/8705846/54960367-919bc080-4f5c-11e9-94f1-dfeaf0682b29.png)

Note that most of the time, I've got this kind of visual glitches, but sometimes, no. I didn't find any reproducible way yet.

@captnfab can you please reopen this issue then? Thank you.

**Comment by glixx** [comment]
@trebmuh Will you update dependencies on the latest versions?
This bug cannot be reprodiced on Mageia Cauldron.

**Comment by trebmuh** [comment]
Hi, my purpose here is to be able to build Pianobooster on the current Debian stable (codename Stretch) without modifying the system. That includes not having to rebuild dependencies.

Curiosity, which dependencies are you thinking of?

**Comment by glixx** [comment]
Patch is welcome

**Comment by glixx** [comment]
![Снимок экрана от 2019-06-17 08-22-25](https://user-images.githubusercontent.com/2681872/59580279-2e43a980-90d9-11e9-9025-cd4b9bc27225.png)
Possibly refreshing of text issue.

**Comment by glixx** [comment]
It depends on video drivers possibly.

**Comment by pianobooster** [comment]
@trebmuh This looks like a video optimisation issue which I saw when it was not disabled. I have now removed this option and I am no longer seeing this issue. Are use seeing this on v0.7.2b? Please close or comment on this issue.

**Comment by trebmuh** [comment]
@pianobooster I didn't see it with 0.7.2b .
I'm closing here and will reopen if it happen again.
