### ISSUE TITLE
Debian branch update

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#122]
Needs to be based on spec file to update files for Debian to build by build.opensuse.org.
dsc file is missing.
Using this service it's possible to build pianobooster for Mageia, OpenSuse and partially for Fedora at the moment.
Arch Linux is planning too.

**Comment by trebmuh** [comment]
The `.dsc` file can be generated with the `debuild` command.

**Comment by glixx** [comment]
@trebmuh will you attach this file?
Anyway Debian package cannot be built by OBS. Do you use OBS to look at problems?

**Comment by glixx** [comment]
Debian files were fully rewritten. So this branch will be deprecated.
At least deb packages builds by OBS now.
We just thinking how to fix
```make install```
https://github.com/captnfab/PianoBooster/issues/119

**Comment by glixx** [comment]
https://github.com/captnfab/PianoBooster/tree/master/pkgs/deb
