### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [pianobooster/PianoBooster#13]
Hi Hello I am looking for open source projects to contribute graphical design, I have done several jobs for free in opensource projects, I would like to know if you are interested that I make a logo for this your project ?.

Greetings

Nuno Jesus

**Comment by trebmuh** [comment]
That would be great to have a new logo for the upcoming new release.
As long as it's for free and the license is compatible with the PianoBooster's one (which is a GPL3).

**Comment by trebmuh** [comment]
That would be great to have a new logo for the upcoming new release.
As long as it's for free and the license is compatible with the PianoBooster's one (which is a GPL3).

@captnfab: what do you think?

**Comment by captnfab** [comment]
I agree! :+1: 
@nunojesus your contribution would be most welcome!
If you have advices about redesigning the interface, you can also make suggestions :)

**Comment by nunojesus** [comment]
Hi, do you have something in your mind? any request? colors?

**Comment by trebmuh** [comment]
Color: mango-fuschia

_(just kidding, I'm colorblind anyway)_

**Comment by trebmuh** [comment]
_(just kidding, I'm colorblind anyway)_

**Comment by captnfab** [comment]
It would be nice if the logo was related to the name of the software or to what it does :)
The software helps people to learn typing on a piano, and gives a "boost" in the learning process (just like blind typing on a keyboard.

**Comment by nunojesus** [comment]
![logotype black piano_1](https://user-images.githubusercontent.com/34600369/40272327-633a96c4-5ba3-11e8-95b8-7015ffed13a1.png)

**Comment by nunojesus** [comment]
What about this
![sem titulo-3](https://user-images.githubusercontent.com/34600369/40272487-b7534f60-5ba5-11e8-8b44-ad156cd25458.png)

**Comment by trebmuh** [comment]
I like the last one really much. 
I'd suggest the color of "Booster" to be a bit stronger since is doesn't appear well when zooming to eg: a 100px image.

:+1: awesome job!

**Comment by nunojesus** [comment]
Hi, In put a bold font in the Booster to be a bit stronger as you requested, I also create 4 icons of the logo, see if you like it.

![sem titulo-2](https://user-images.githubusercontent.com/34600369/40273940-83bcec52-5bc2-11e8-9192-888b3ce61e03.png)

**Comment by captnfab** [comment]
Wow, amazing. @nunojesus: that's nice work, you're quite skilled.

**Comment by nunojesus** [comment]
Thanks for your words :)

Can I make the png files and make a PR?

**Comment by trebmuh** [comment]
Awesome. Great job @nunojesus .
Can you provide the files on a svg format as well?

**Comment by nunojesus** [comment]
Yes i can, I will try to send today. Greetings

**Comment by captnfab** [comment]
Yep, please do a PR :+1:

**Comment by captnfab** [comment]
Huge thanks @nunojesus :+1:

**Comment by nunojesus** [comment]
You dont need to thank me, Im happy that you like it.

Greetings.

**Comment by trebmuh** [comment]
Awesome job @nunojesus !

Should we close this thread now guys?

**Comment by glixx** [comment]
> Hi Hello I am looking for open source projects to contribute graphical design, I have done several jobs for free in opensource projects

@nunojesus , I'm looking for graphical design for open source projects. Please contact with me.
