### ISSUE TITLE
removing the weblate translation thing

### ISSUE THREAD

**Issue by trebmuh** [pianobooster/PianoBooster#141]
@glixx , because you changed the way translations are done, you should remove pianobooster's translation from Weblate. This would avoid people [to keep working on it there](https://hosted.weblate.org/translate/piano-booster/translations/nb_NO/?checksum=ac549751d4a1b9f3#comments) and then waste their time.

**Comment by trebmuh** [comment]
[Here too](https://hosted.weblate.org/translate/weblate/master/fi/?type=all&offset=468#comments)

**Comment by glixx** [comment]
@captnfab removed weblate project. I don't know why it is still there.
Current translation project is here https://www.transifex.com/Magic/pianobooster

**Comment by glixx** [comment]
weblate project is not available.
