### ISSUE TITLE
OpenBSD build fails.

### ISSUE THREAD

**Issue by yason** [pianobooster/PianoBooster#146]
Hi!
Building of PianoBooster fails on OpenBSD-current with the following error:

../src/GuiPreferencesDialog.cpp:64:5: error: 'QJsonObject' does not refer to a value
    QJsonObject rootLangs;
    ^
/usr/local/include/X11/qt5/QtCore/qpluginloader.h:54:7: note: declared here
class QJsonObject;
      ^
../src/GuiPreferencesDialog.cpp:79:13: error: use of undeclared identifier 'rootLangs'
            rootLangs = document.object();
            ^
../src/GuiPreferencesDialog.cpp:103:17: error: use of undeclared identifier 'rootLangs'
            if (rootLangs.value(lang_code).toObject().value("nativeName").isString()){
                ^
../src/GuiPreferencesDialog.cpp:104:32: error: use of undeclared identifier 'rootLangs'
                languageName = rootLangs.value(lang_code).toObject().value("nativeName").toStrin
g();
                               ^
4 errors generated.

Arch amd64
Compiler clang 7.0.1
Qt 5.9.7

Full log attached
[pianobooster-0.6.8.1.log](https://github.com/captnfab/PianoBooster/files/3343927/pianobooster-0.6.8.1.log)

**Comment by glixx** [comment]
We will add option to build without languages.

**Comment by glixx** [comment]
Please try ```NO_LANGS=ON```

**Comment by glixx** [comment]
Fixed by building without localization.
