### ISSUE TITLE
Sign releases with gpg

### ISSUE THREAD

**Issue by captnfab** [pianobooster/PianoBooster#15]

**Comment by barak** [comment]
Just `git tag --sign vVERSION` the release-creating git tags when you create them, that's enough to establish the chain of trust if the release tarball are generated automatically from the tagged commits, which they are.

**Comment by barak** [comment]
Oh noes, the latest release tag `v0.7.0` isn't signed how can I ever trust it?

**Comment by glixx** [comment]
No one release tag was signed. I do preffer do not sign them.
