### ISSUE TITLE
Install in /usr instead of /usr/locale

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#156]
make install:
qmake is ok. cmake is not ok.

**Comment by hpladds** [comment]
Are these two issues related? Both involve install into /usr rather than /usr/local. 

https://github.com/captnfab/PianoBooster/issues/96

**Comment by glixx** [comment]
It depends on distribution. Cmake installs into /usr/local in Arch Linux, BSD Unix by default.

**Comment by glixx** [comment]
Cannot be fixed. Otherwise it breaks packages building.
