### ISSUE TITLE
Please replace share/games/pianobooster/ with a variable, for example DATA_DIR

### ISSUE THREAD

**Issue by yurivict** [pianobooster/PianoBooster#165]
It is currently hard-coded to ```share/games/pianobooster/``` and this is difficult because it needs to be patched to bring it to a standard value.

You should have something like:
```
if (${DATA_DIR} EQUAL "")
  set(DATA_DIR " share/games/pianobooster")
endif()
```

**Comment by glixx** [comment]
Done

**Comment by yurivict** [comment]
Thanks!
