### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by captnfab** [pianobooster/PianoBooster#17]
Please help us translate PianoBooster in many languages thanks to the weblate : https://hosted.weblate.org/projects/piano-booster/translations/

**Comment by trebmuh** [comment]
Nice to see PianoBooster using hosted.weblate. Good job @captnfab !
Out of curiosity, did you set up an automatic integration with the (right here) github's repo?

**Comment by captnfab** [comment]
Yep :)

**Comment by trebmuh** [comment]
Awesome :+1:

**Comment by glixx** [comment]
How to commit if translation was done?

**Comment by trebmuh** [comment]
@glixx did you make the translation in [weblate](https://hosted.weblate.org/projects/piano-booster/translations/) ?

**Comment by glixx** [comment]
Yes. I made Russian the first. It was not commited here. I made Czech translation the second. It was commited here automatically.

**Comment by trebmuh** [comment]
@captnfab : a Russian translation file seems to have been commited/merged here but is empty. See https://github.com/captnfab/PianoBooster/commit/10a599a70ea4ce9025f486b6bd2edfe443a3e6a4

**Comment by glixx** [comment]
It was made just when I started new language, but when I finished it, then it was not commited.
So contact with weblate to fix issue and commit all translations time by time manually especially before release. I am not sure they were commited fully.
The best way to have button on weblate side to commit translation force.

**Comment by glixx** [comment]
Czech and Russian translations were commited today automatically with delay around 1-2 days.

**Comment by trebmuh** [comment]
sweet, so no issue here, just need to wait a little bit maybe

**Comment by glixx** [comment]
https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commits

**Comment by glixx** [comment]
Not all strings were marked for translation.
(
for example:

This is a simplified version of Clair De La Lune that uses only the three notes C D and E from your right hand. First find middle C and always uses your thumb for this note, then for D use your first finger and for E and middle finger. 
Hint: If you are a complete beginner try the pieces from the Beginner Course first. 
)
Needs to use Qttranslator to translate system strings (context menu, buttons, etc.): https://github.com/captnfab/PianoBooster/issues/28
Dialog About were not translated.
Some strings were translated, but not in use.

**Comment by glixx** [comment]
> Needs to use Qttranslator to translate system strings (context menu, buttons, etc.): #28

Fixed by https://github.com/captnfab/PianoBooster/pull/29/commits/6a2ef0c8322d88ca22801d17e18fd640e70c0c74

> Some strings were translated, but not in use.

Fixed by https://github.com/captnfab/PianoBooster/pull/30/commits/8cb36f7a106dfdb372b4d236370bd1947fcb9710

> Dialog About were not translated.

Fixed by https://github.com/captnfab/PianoBooster/pull/30/commits/81398a8122cf1df84c0fa62a45cae81505b37bc5

**Comment by glixx** [comment]
Translations were imported from DoudouLinux.
Please delete nl_XD, ig: nothing was imported.

**Comment by glixx** [comment]
> Please delete nl_XD, ig: nothing was imported.

Ping

**Comment by glixx** [comment]
> Please help us translate PianoBooster in many languages thanks to the weblate : 

At the moment you have many translations. This issue is not actual already.

**Comment by glixx** [comment]
Needs to use any format, that weblate supports to translate html files, cause it does not support HTML files.
Note: transifex supports TS and HTML files. So it's better for this project.

**Comment by captnfab** [comment]
Transifex is a proprietary platform, that's why I went to weblate. I'm not sure how to deal with this problem. I'm not aware of any tool in Qt to manage help and documentation in an i18n-friendly way. Any idea?

**Comment by glixx** [comment]
Music is now translatable by ts files: https://github.com/captnfab/PianoBooster/pull/45
So this bug can be closed.

**Comment by glixx** [comment]
Just configure weblate to translate new music_blank.ts

**Comment by glixx** [comment]
> Just configure weblate to translate new music_blank.ts

Still not done :(
Please run lupdate again.

**Comment by glixx** [comment]
No more activity.

**Comment by glixx** [comment]
@captnfab, where are you?

**Comment by glixx** [comment]
Translations are available now on transifex: https://www.transifex.com/Magic/pianobooster
Weblate translations project was closed, it did not allow to translate more than 1 source for free, but at the moment we have 4 sources to translate.
You're welcome to translate on transifex.

**Comment by trebmuh** [comment]
I didn't think that this is a good move. Specifically without any talks nor consensus before acting.

1st they are people (like me) who already committed translation whether with a PR against this repo, or on weblate. I'll not subscribed myself to another (private and non-free) tool like weblate.

2nd why did you make a move to transifex? Your explanation above isn't clear enough. What "4" different source are you talking about?

**Comment by glixx** [comment]
It was discussed with @captnfab by email.
All translations were moved on transifex. It's not mandatory to use transifex. You can translate by PR too: https://github.com/captnfab/PianoBooster#translations
Weblate is too stupid.
90% open source code are translating by transifex. My team has 1000+ translators.
We have 2 ts files and 2 desktop files. Weblate does not support this task for free.

**Comment by trebmuh** [comment]
> It was discussed with @captnfab by email.

Discussion happening behind the curtains like this are definitely not the best way to build a collaboration process within an opensource project.


> All translations were moved on transifex. It's not mandatory to use transifex. You can translate by PR too.

Good to know. Thanks.


> Weblate is too stupid.

No it's not. It is trying to build an economic system which aims to be ethic IIUC. You can like like or not, but insulting people doing free software and trying to make a living of it is just crazyness. Don't forget that Transifex is a business and, as usual, if the product is free, then it usually means that **you** are the product. At the top of that, Weblate is making free software, Transifex not and then, I'm all for using and supporting Weblate instead of Transifex.


> 90% open source code are translating by transifex.

Just LOL... I'm doing free software translations on a daily basis and had contributed so to something like over 50 or 60 different projects and know what? I don't have a Transifex account.

Moreover, about this "90% thing"... 90% of desktop computer are using Windows... then is it an good enough reason/argument to leave other OSes and use Windows?

This just sounding like an argument from authority. Nice try but it didn't hit the goal.


> My team has 1000+ translators.

And...?


> We have 2 ts files and 2 desktop files. Weblate does not support this task for free.

I'm pretty sure that some free software projects have a free account on Weblate with more than that. Probably just a matter of discussing with Weblate's people.

Question: did you try to contact them or did you decide to go with transifex "because that's easier for you"?

**Comment by glixx** [comment]
Weblate is business, it support only 1 file for free. Support is stupid. They ignore bugreports with resolution: you're welcome with patches. What? I do not have plans to develop weblate, I need translations only. Transifex is free for open source.
Translators follow project, but not project follows translators.
It was objective decition.
If you do not like transifex you're free to translate by PR.

@trebmuh only one file was translated in French, but 3 files was not. They are waiting for your contribution.

**Comment by trebmuh** [comment]
> Weblate is business

Yes it is, if you re-read carefully, I talked about different business models. AFAIK, Weblate is making free software, is hosting for free small software, and is selling advanced support to customer. Transifex is making proprietary software, is hosting free software, and is making money with customer support too (+ they have informations about users, go know what they do with that...). That's different business models and I much prefer the one from Weblate.

> Support is stupid.

Well, keep this kind of insults for you please, they're not making your argument stronger. That's actually quite the opposite to be honest.

> They ignore bugreports with resolution: you're welcome with patches. What? I do not have plans to develop Weblate, I need translations only.

Well, that's the kind of answer [you're able to give yourself to other](https://github.com/captnfab/PianoBooster/issues/12#issuecomment-498078273), isn't ? I don't see the problem. They are providing a free hosting, and are not committed to sort out everything. Fair enough.

> Transifex is free for open source.

You're missing the point. They are free of money for free software. But they aren't free software AFAIK (please correct me if I'm wrong here). Already wrote it above, "in a capitalistic system, if the product is free, then most likely, you are the product".

>  It was objective decition.

Not from my point of view. That was **your** decision, no talks upwards, no discussions with current translators (me), just a decision fitting **your** need. Nothing related to "objective".

>  If you do not like transifex you're free to translate by PR.

I could do with that, even if the workflow is less easy than with Weblate now (thanks for having taking an "objective decision" impacting my work without asking/discussing it first...

> @trebmuh only one file was translated in French, but 3 files was not. They are waiting for your contribution.

I'm not that sure I want to keep contributing here if your style is to have un-open and un-collaborative discussions behind the curtains (ie: by personal emails), then making auto-discussed-with-yourself decision,  and then arguing that it is "objective decision" when things are done. This kind of process isn't opening for wide collaboration.

> @trebmuh only one file was translated in French, but 3 files was not. They are waiting for your contribution.

Given what I said just above, I'm not sure that I'll keep translating and reporting bugs/suggestion. Will see later.
