### ISSUE TITLE
No soundfonts are found in the "soundfont" directory

### ISSUE THREAD

**Issue by yurivict** [pianobooster/PianoBooster#170]
https://github.com/captnfab/PianoBooster/blob/master/src/MidiDeviceFluidSynth.cpp#L62

Where are they supposed to come from? Who installs the?

**Comment by glixx** [comment]
Did you build with USE_FLUIDSYNTH=ON ?
In this case it will be Fluidsynth tab in Settings where button of loading soundfonts is present.

**Comment by glixx** [comment]
There is WITH_FLUIDSYNTH flag too. It installs desktop file and wrapper script tools/fluidsynth/pianobooster-fluidsynth.
But for BSD Unix needs to configure JACK first to use realtime by user or disable realtime. By default only root has permissions on realtime in BSD Unix, but jackd starts in realtime mode by default and user has no permissions.
Nobody knows how to give permissions to user on realtime in BSD Unix even forum gurus. This is a BSD Unix bug.

**Comment by yurivict** [comment]
> Did you build with USE_FLUIDSYNTH=ON ?

yes

> In this case it will be Fluidsynth tab in Settings where button of loading soundfonts is present.

Currently it just silently shows no fonts.

1. PianoBooster should suggest this to the user when the list of midi devices from FluidSynth is empty.
2. PianoBooster should have a cmake option with a sf2 directory. On FreeBSD FluidSynth installs a lot of sound fonts into ${prefix}/share/sounds/sf2 You should allow this directory to be configured in cmake and just default to the installed fonts.

**Comment by glixx** [comment]
Pianobooster does not work with FluidSynth as sub-process (https://github.com/captnfab/PianoBooster/issues/179), but it generates config file now to be used by pianobooster-fluidsynth script and it suggests soundfonts now.
