### ISSUE TITLE
OpenGL dev for RaspberryPI

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#171]
I’m trying to run PianoBooster (a game that teaches kids to play piano) on a RaspberryPi 3. It requires OpenGL (not OpenGL ES). Pianobooster works wonderfully on my AMD64 Desktop machine, and almost works perfectly my Raspberry Pi except for the rendering of the musical score. It displays a three lined score.

Please see RaspPi screen capture. https://drive.google.com/open?id=0Bz6ELo6H8KYUQ0IxNlhmZEg1TW8
vs
Desktop screen capture: https://drive.google.com/open?id=0Bz6ELo6H8KYUU3c2Yzd1MnAwdkk

Interestingly the game “works” on RaspPi; however, players need to make an educated guess about what piano key needs to be played next.

I believe the problem lies in the developmental OpenGL driver for Rasp Pi, and there is little I can do but wait for further progress. But perhaps there is a coding error that needs fixing? The code can be found here:
https://github.com/ecashin/pianobory.git

Original post: https://community.khronos.org/t/opengl-dev-for-raspberrypi/76042

**Comment by glixx** [comment]
![2017-05-24-182257_1360x768_scrot](https://user-images.githubusercontent.com/2681872/60933067-76fe1500-a2c9-11e9-8da6-ff429c5668be.png)
![DeskTop_PianoB_](https://user-images.githubusercontent.com/2681872/60933070-76fe1500-a2c9-11e9-88bb-6c4d12b79f68.png)

**Comment by glixx** [comment]
Solution is merging with https://github.com/hpladds/PiPianoBooster

**Comment by glixx** [comment]
@d4s Your patch fixes this issue?

**Comment by hpladds** [comment]
On Tue, Jul 9, 2019 at 9:17 PM glixx <notifications@github.com> wrote:

> Solution is merging with https://github.com/hpladds/PiPianoBooster
>

This issue was related to a glitch found in the PB ver 0.6.4 in the Debian
"Games" repository. The problem did not exist in the apt-get repository of
Raspbian.
