### ISSUE TITLE
Run fluidsynth and timidity as processes

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#179]
Needs to teach program to start fluidsynth and timidity as processes.
This is future proposal for the next version (not for 0.7.0)

**Comment by pianobooster** [comment]
When I first test with pianobooster-timitidy . i did hear some distortion. but this can be fixed by using this command line `timidity -iA -B2,8 -Os -EFreverb=0`. however both fluidsynth and timidity already run in there own processes.
