### ISSUE TITLE
Can't connect keyboard

### ISSUE THREAD

**Issue by C0rn3j** [pianobooster/PianoBooster#197]
I've a PSR-E363 connected via USB to my Arch Linux desktop.

Trying to use Flowkey MIDI detection in Chromium works perfectly, but I can't see the keyboard in Pianobooster at all.

I've installed Pianobooster via [AUR/pianobooster-qt5-git](https://aur.archlinux.org/packages/pianobooster-qt5-git/)

![image](https://user-images.githubusercontent.com/1641362/63587767-0ecb7000-c5a5-11e9-83c7-521e92d0488d.png)

Flowkey:
![image](https://user-images.githubusercontent.com/1641362/63587831-3f130e80-c5a5-11e9-8478-ebba8f26e919.png)

Dmesg:
```
[92784.460969] usb 1-1: new full-speed USB device number 4 using xhci_hcd
[92784.858810] usb 1-1: New USB device found, idVendor=0499, idProduct=1710, bcdDevice= 1.00
[92784.858812] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[92784.858813] usb 1-1: Product: Digital Keyboard
[92784.858814] usb 1-1: Manufacturer: YAMAHA Corporation
```

```
[0] % pianobooster
Icon theme "gnome" not found.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

MidiOutJack::initialize: JACK server not running?

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

MidiOutJack::initialize: JACK server not running?

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

MidiInJack::initialize: JACK server not running?

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

MidiInJack::initialize: JACK server not running?

Info: applicationDirPath=/usr/bin
ERROR: Cannot find BoosterMusicBooks.zip
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
...
```

**Comment by trebmuh** [comment]
`MidiInJack::initialize: JACK server not running?`

and

```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```

Do you have a jack server running?

**Comment by glixx** [comment]
We do not support aur repositories. Try our package for Arch Linux https://software.opensuse.org/download.html?project=home%3Aloginov_alex_valer&package=pianobooster
and read FAQ file about Arch Linux.

**Comment by glixx** [comment]
https://github.com/captnfab/PianoBooster/blob/master/doc/faq.md

**Comment by C0rn3j** [comment]
If you have a working Arch Linux package, why won't you upload it to AUR and support that? It'd work great in addition to the custom repositories for when someone prefers to use those.

The package I used compiles cleanly from this git repo (after removing a redundant patch), so I don't see why it would cause an issue.

Your FAQ suggests to add the user to the `audio` group, which was deprecated some while ago - https://wiki.archlinux.org/index.php/Users_and_groups#Pre-systemd_groups

Seems like you want to install `realtime-privileges` and add the user to the `realtime` group nowadays. 

https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit

I've gotten jack2 to work to the point where Piano Booster at least stops complaining, but I still see no input device.

![image](https://user-images.githubusercontent.com/1641362/63593662-b7cd9700-c5b4-11e9-8d60-0e4324d68afb.png)

**Comment by glixx** [comment]
Your package is broken. It could not even to find BoosterMusicBooks.zip.
We have pianobooster-fluidsynth script to run pianobooster with fluidsynth and it goes with our package.
Supporting workable packages in aur is work of Arch Linux maintainers. We just provide example package and FAQ.

**Comment by C0rn3j** [comment]
Where can I find the PKGBUILD you used for building the Arch package?

EDIT: https://github.com/captnfab/PianoBooster/blob/master/pkgs/arch/PKGBUILD

**Comment by glixx** [comment]
In source code.

**Comment by glixx** [comment]
Is it ok now?

**Comment by C0rn3j** [comment]
I've compiled the package from your PKGBUILD and it indeed does detect the keyboard now. 

```
mkdir -p /tmp/pianobooster && cd /tmp/pianobooster
wget -O PKGBUILD https://raw.githubusercontent.com/captnfab/PianoBooster/master/pkgs/arch/PKGBUILD
git clone https://github.com/captnfab/PianoBooster
mv PianoBooster pianobooster-0.7.0
tar -cvf pianobooster-0.7.0.tar pianobooster-0.7.0 && gzip pianobooster-0.7.0.tar
makepkg -sri
```

![image](https://user-images.githubusercontent.com/1641362/63652704-8e06a280-c763-11e9-813b-0f9f95d4ac21.png)


Output seems fine, however I can't get Piano Booster to recognize correct note input. It seems to detect wrong input just fine however. To be exact, it looks like it's ignoring single-note input and only registering multiple notes at once, meaning I can't ever produce the correct input for a single note.

 I'm probably doing something wrong, but I can't figure out what.

![image](https://user-images.githubusercontent.com/1641362/63652825-f86c1280-c764-11e9-8f07-336db3d40345.png)
