### ISSUE TITLE
Pianobooster 0.7.0 hung on CODE61

### ISSUE THREAD

**Issue by tuxstef** [pianobooster/PianoBooster#204]
Hello,
Pianobooster 0.7.0 is using a lot CPU usage while listening to CODE61(with velocity sensitive keys) keyboard. Pianobooster gets stuck and the system is afterwards in MIDI "panic" mode. The keyboard and sound output playing a midi file is fine.
Installed is jack 0.4.5 and Qsynth 0.5.0 (including fluidsynth 1.1.9)
I am using Ubuntu 18.04.

Compile options:
cmake -DUSE_SYSTEM_FONT=ON -DINSTALL_ALL_LANGS=ON -DWITH_MAN=ON -DNO_LICENSE=ON -DNO_CHANGELOG=O -DCMAKE_BUILD_TYPE=Debug . -DCMAKE_INSTALL_PREFIX="/opt/pianobooster"

I uninstalled the systems's rtmidi libs before compiling.

Pianoboosters output (while long pressing a random key):
Info: Tracks 13 PPQN 480
Warn: Midi Tempo 100000,000000  ppqn 480 500000
Info: Active both
Info: Using Pianist Channels 1 + 8
Info: midi input  0x90, 0x28, 0x1e,
Info: midi input  0xd0, 0x2,
Info: midi input  0xd0, 0x6,
Info: midi input  0xd0, 0x9,
Info: midi input  0xd0, 0xe,
Info: midi input  0xd0, 0x12,
Info: midi input  0xd0, 0x15,
Info: midi input  0xd0, 0x19,
Info: midi input  0xd0, 0x1c,
Info: midi input  0xd0, 0x1f,
Info: midi input  0xd0, 0x1a,
Info: midi input  0xd0, 0x17,
Info: midi input  0xd0, 0x14,
Info: midi input  0xd0, 0xf,
Info: midi input  0xd0, 0xc,
Info: midi input  0xd0, 0x9,
Info: midi input  0xd0, 0x5,
Info: midi input  0xd0, 0x7,
Info: midi input  0xd0, 0xb,
Info: midi input  0xd0, 0xf,
Info: midi input  0xd0, 0x13,
Info: midi input  0xd0, 0x15,
Info: midi input  0xd0, 0x19,
Info: midi input  0xd0, 0x1b,
Info: midi input  0xd0, 0x1f,
Info: midi input  0xd0, 0x25,
Info: midi input  0xd0, 0x27,
Info: midi input  0xd0, 0x29,
Info: midi input  0xd0, 0x2b,
Info: midi input  0xd0, 0x27,
Info: midi input  0xd0, 0x23,
Info: midi input  0xd0, 0x1e,
Info: midi input  0xd0, 0x1b,
Info: midi input  0xd0, 0x15,
Info: midi input  0xd0, 0xf,
Info: midi input  0xd0, 0xb,
Info: midi input  0xd0, 0x2,
Info: midi input  0xd0, 0x0,

What further infos are needed to solve this issue?

**Comment by tuxstef** [comment]
Here's the jack connection list:
jack_lsp -c
system:playback_1
   qsynth:left
system:playback_2
   qsynth:right
alsa_midi:Midi Through Port-0 (out)
alsa_midi:Midi Through Port-0 (in)
alsa_midi:Code 61 MIDI 1 (out)
   RtMidi Input Client:RtMidi
alsa_midi:Code 61 MIDI 1 (in)
alsa_midi:Code 61 MIDI 2 (out)
alsa_midi:Code 61 MIDI 2 (in)
alsa_midi:Code 61 MIDI 3 (out)
alsa_midi:Code 61 MIDI 3 (in)
alsa_midi:Code 61 MIDI 4 (out)
alsa_midi:Code 61 MIDI 4 (in)
qsynth:left
   system:playback_1
qsynth:right
   system:playback_2
RtMidi Input Client:RtMidi
   alsa_midi:Code 61 MIDI 1 (out)
qsynth:midi
   RtMidi Output Client:RtMidi
RtMidi Output Client:RtMidi
   qsynth:midi

Pianobooster config for i/o:
input: alsa_midi:Code 61 MIDI 1 (out)
output:  qsynth:midi

**Comment by pianobooster** [comment]
Please can you retest on develop branch. the high cpu usage is a known problem which may get fixed eventually. It is now no longer necessary to use or install jack. and the compile options cmake .. now work fine. please let me know if the code on the develop branch fixes your problem so i can close this issue. thanks

**Comment by tuxstef** [comment]
Hello,
sorry for the delay..
My CODE 61 now works fine with 0.7.2b (single keys and multiple work fine). Other versions I have not tested. A long term test (many midi files) was not performed.
