### ISSUE TITLE
Pianobooster not playing midi input

### ISSUE THREAD

**Issue by tuxstef** [pianobooster/PianoBooster#206]
Hello,
as pianobooster was not playing the midi input from my CODE 61 I decided to change the code because of missing bytes in m_inputMessage if the function CMidiEvent CMidiDeviceRt::readMidiInput() reads the data from m_inputMessage.

Pianobooster was configured for using the integrated rtmidi 4.0.0 library.
The host and build system is Ubuntu 19.10.

One hint: If Follow Through errors and Follow You is checked the sound does not stopped, every chord which was played is not going to stop playing..

Some changes were made to repot this:

```
diff -u PianoBooster-master.edit/src/Conductor.cpp PianoBooster-master/src/Conductor.cpp
--- PianoBooster-master.edit/src/Conductor.cpp  2019-11-29 20:38:45.048028641 +0100
+++ PianoBooster-master/src/Conductor.cpp       2019-09-03 22:25:38.000000000 +0200
@@ -630,7 +630,6 @@
         CChord chord;
         int i;
         CMidiEvent newNote = inputNote;
-
         if (inputNote.type() == MIDI_NOTE_ON || inputNote.type() == MIDI_NOTE_OFF)
         {
             chord = m_wantedChord;
@@ -685,7 +684,7 @@
     }
 }
 
-void CConductor::(CMidiEvent inputNote)
+void CConductor::pianistInput(CMidiEvent inputNote)
 {
     bool goodSound = true;
 
@@ -982,9 +981,8 @@
     if (!m_followPlayingTimeOut)
         m_pianistTiming += ticks;
 
-//    while (checkMidiInput() > 0)
-//        expandPianistInput(readMidiInput());
-    expandPianistInput(readMidiInput());
+    while (checkMidiInput() > 0)
+        expandPianistInput(readMidiInput());
 
     if (getfollowState() == PB_FOLLOW_waiting )
     {


 and

diff -u PianoBooster-master.edit/src/MidiDeviceRt.cpp PianoBooster-master/src/MidiDeviceRt.cpp
--- PianoBooster-master.edit/src/MidiDeviceRt.cpp       2019-11-29 20:38:45.108028639 +0100
+++ PianoBooster-master/src/MidiDeviceRt.cpp    2019-09-03 22:25:38.000000000 +0200
@@ -28,6 +28,7 @@
 
 #include "MidiDeviceRt.h"
 
+
 CMidiDeviceRt::CMidiDeviceRt()
 {
     try {
@@ -241,11 +242,6 @@
     CMidiEvent midiEvent;
     unsigned int channel;
 
-    m_midiin->getMessage( &m_inputMessage );
-
-    if (m_midiPorts[0] >= 0 && m_inputMessage.size() > 0) {
-
-
 
     if (Cfg::midiInputDump)
     {
@@ -299,10 +295,7 @@
     }
 
     m_inputMessage.clear();
-
-    }
     return midiEvent;
-
 }
```

**Comment by louis-barman** [comment]
OK this is now fixed please check the the develop branch of my fork of the pianobooster project (see https://github.com/louis-barman/PianoBooster) Please can you confirm this is fixed so that this issue can be closed.

The fix was MidiDevice.cpp line 136 which add had an unwanted extra line `m_selectedMidiInputDevice->checkMidiInput();`

also Please see my comment on this https://github.com/captnfab/PianoBooster/issues/207#issuecomment-576460828

**Comment by pianobooster** [comment]
Fixed. Please see the code in the develop branch. Thank for raising this.
