### ISSUE TITLE
tip display is unredeable

### ISSUE THREAD

**Issue by trebmuh** [pianobooster/PianoBooster#209]
![before](https://user-images.githubusercontent.com/8705846/71686771-67edb080-2d9c-11ea-93b7-be9026ea1dba.png)

Then, in ~/Music/BoosterMusicBooks3/Booster\ Music/InfoPages/01-ClairDeLaLune_en.html from:

```
<body bgcolor="#FFFFC0"><p>This is a simplified version of <strong>Clair De La Lune</strong> that uses only the three notes <strong>C D</strong> and <strong>E</strong> from your right hand. First find <strong>middle C</strong> and always use your <strong>thumb</strong> for this note, then for <strong>D</strong> use your <strong>first finger</strong> and for <strong>E</strong> use <strong>middle finger</strong>.</p>

<font color="#ff0000"><p><strong>Hint:</strong> <em>If you are a complete beginner try the pieces from the <strong>Beginner Course</strong> first.</em></p></font></body>
```

to 

```
<body bgcolor="#FFFFC0"><font color="#000000"><p>This is a simplified version of <strong>Clair De La Lune</strong> that uses only the three notes <strong>C D</strong> and <strong>E</strong> from your right hand. First find <strong>middle C</strong> and always use your <strong>thumb</strong> for this note, then for <strong>D</strong> use your <strong>first finger</strong> and for <strong>E</strong> use <strong>middle finger</strong>.</p></font>

<font color="#ff0000"><p><strong>Hint:</strong> <em>If you are a complete beginner try the pieces from the <strong>Beginner Course</strong> first.</em></p></font></body>
```

and I have that:

![after](https://user-images.githubusercontent.com/8705846/71686843-a6836b00-2d9c-11ea-8ee8-b57c73999da1.png)

which is much more readable.

The same is applying for all the song embedded with PianoBooster.

It looks to me that those html files are generated during the build.

Please fix this in the code.

**Comment by louis-barman** [comment]
The size of the tip window has now been larger and the font size bigger. please check the the develop branch of my fork of the pianobooster project (see https://github.com/louis-barman/PianoBooster) for the code change.

**Comment by trebmuh** [comment]
Just to let you know @louis-barman that I'm not in a position to be able to test this before around beginning of March. Feel free to ping me then.

**Comment by pianobooster** [comment]
Fixed on the develop branch so closing. Thanks for raising this.
