### ISSUE TITLE
Plans for new Piano Booster release version 0.7.2

### ISSUE THREAD

**Issue by louis-barman** [pianobooster/PianoBooster#212]
Hello all, I am the original author of Piano Booster and after many years of neglect plan to be more active in this project in future. I have been testing out the current release version 7.0 and also the master branch and there are a number of problems with it. The most serious problem is the MIDI input does not work so any notes played on a connected MIDI piano keyboard get ignored. The whole purpose of Piano Booster is to teach the piano and encourage users to learn to read sheet music by turning it into an educational game. For this reason version 7.0 is unusable for it’s intended purpose and so we need to get a new bug fix version out as soon as we can. Also there is a new version of the Linux OS Ubuntu 2020.4 release LTS (long term support) coming up soon that currently has pianobooster version 7.0 in that release.

Also since there is already a version 7.1 in the master branch to avoid any confusion I suggest we move to version 7.2. I hope that we can get version 7.2 ready in time but it will only be a Linux only release. Also as is standard practice we will only put release code on the `master` branch and all pull request should be to the `develop`. Also the version number should have the string `-SNAPSHOT` appended to the version name when submitting code to the develop branch.

# General goals for this and future releases
* The Users Interface (UI) should be straight forward (not technical) so that even children can use it. It should not need any technical skill to use it or to set it up.
* The default build should always work with no options. (Build via the command line using ‘cmake ..’ )
* There should be less build options as this simplifies testing. In theory all the different build options combinations would need to be tested.
 * There should be as few build dependencies as possible as each added dependency makes it harder to support when the dependencies get changed and updated.
# Proposed changes for version 7.2
So below are the things that I am planning to sort out in version 7.2 and I plan to do this mostly myself as the code changes are all fairly straight forward. This will mainly be a bug fix release and will not include any new features.

* Fix the MIDI input problem (DONE)
* Fix so that a default build (cmake with no parameters) produces a workable PB executable. (DONE: adding the USE_ALSA parameter which defaults to ON)
 * Proposal to remove TiMidity completely from the source code. This only adds unnecessary complication to PianoBooster. However users can still very easily use timidity with piano booster all they have to do is type `timidity -iA -B2,8 -Os -EFreverb=0` on the command line. I will add these instructions to the readme and also to the website.  Also fluidsynth works much better than TiMidity in my opinion so that is the better synth to use.
* I could not get any of the built-in fluidsynth (USE_FLUIDSYNTH option) to work at all. So for now I propose to mark this as untested and to also set this option to OFF in all of the packages distribution configurations.
 * The pianobooster-fluidsynth and the painobooster-timidity desktop scripts and the WITH_FLUIDSYNTH  and WITH_TIMIDITY doe not add any value and only complicate things so I propose to remove these options. Instead we should add simple clear instructions on how the users can easily start these synths. In the long term I plan to integrate fluidsynth within Piano Booster so that you get sound straight away without any configuration required.
* I could not get Piano Booster to work with JACK. if any one knows how to do this then please let me know. For this reason I have made the dependency on JACK optional and marked this option as untested. I recommend we set this option to OFF in all the include package options.
* Removal of the dependencies on the external RTMIDI library by using the USE_SYSTEM_RTMIDI option and only use the included 3rd party source code instead. The trouble with this is option is that doubles the support and tests when the included 3rd party source code works fine.
* I would like the PianoBooster app about dialogue and the app help pages to point back to my site at http://pianobooster.sourceforge.net/ which I plan to update this site with more information in the future. The GitHub site https://github.com/captnfab/PianoBooster which it has been changed to is not really suitable for the end users who are not coders.
* Bug: The coloured notes are on by default which is confusing and do not turn off correctly.  (FIXED).
* Merge the build options NO_LICENSE  and NO_CHANGELOG into the NO_DOCS option.
* Change the default startup song on a fresh install from “BoosterMusic/01-ClairDeLaLune.mid” to "BeginnerCourse/01-StartWithMiddleC.mid” as beginners really need to start at the beginning.

When we have an a version 7.2-RC (Release Candidate) available then I would like help with testing these changes on as many environments as possible especially I would like help with those who have a MIDI keyboard and can use piano booster to play along.

If you are a Windows or a Mac users sorry you will have to wait until version 7.3 (or try out Linux on your PC).

There is a reference to this issue has been posted to the piano booster develop forum you can reply there if prefer. see http://piano-booster.2625608.n2.nabble.com/Piano-Booster-Development-f2625691.html

**Comment by glixx** [comment]
I'm fully not agree. It brokes a lot platforms and does not follow policy of distributions.

**Comment by glixx** [comment]
> The Users Interface (UI) should be straight forward (not technical) so that even children can use it. It should not need any technical skill to use it or to set it up.

It's already ok, nothing to change.

> The default build should always work with no options. (Build via the command line using ‘cmake ..’ )

No, it must not, it's impossible. Each platform has own options.

> There should be less build options as this simplifies testing. In theory all the different build options combinations would need to be tested.

No. It must be more options for all cases.

> There should be as few build dependencies as possible as each added dependency makes it harder to support when the dependencies get changed and updated.

They are already minimal, nothing to change.

> Fix so that a default build (cmake with no parameters) produces a workable PB executable. (DONE: adding the USE_ALSA parameter which defaults to ON)

It breaks building on other platforms. If it works on your Ubuntu, it means nothing. Ubuntu is not Linux.

>   Proposal to remove TiMidity completely from the source code.

TiMidity is main, FluidSynth is optional.

> However users can still very easily use timidity with piano booster all they have to do is type timidity -iA -B2,8 -Os -EFreverb=0 on the command line.

Absolutely no. If it works on your Ubuntu, it means nothing. Ubuntu is not Linux. timidity is different compilled on different platforms: https://github.com/captnfab/PianoBooster/blob/master/tools/timidity/pianobooster-timidity

> I will add these instructions to the readme and also to the website.

Readme is already full, do not need to add your wrong instructions.

> Also fluidsynth works much better than TiMidity in my opinion so that is the better synth to use.

No differences in work, but with fluidsynth size of pianobooster is too big, sound fonts are big. timidity is smallest.

>  I could not get any of the built-in fluidsynth (USE_FLUIDSYNTH option) to work at all. So for now I propose to mark this as untested and to also set this option to OFF in all of the packages distribution configurations.

It works fine.

> The pianobooster-fluidsynth and the painobooster-timidity desktop scripts and the WITH_FLUIDSYNTH and WITH_TIMIDITY doe not add any value and only complicate things so I propose to remove these options.

Absolutely no. They are part of package or subpackage.

> Instead we should add simple clear instructions on how the users can easily start these synths.

Instructions are already full. Users do not need to use console, but run from menu.

> In the long term I plan to integrate fluidsynth within Piano Booster so that you get sound straight away without any configuration required.

Do not need without timidity integration too.

>  I could not get Piano Booster to work with JACK.

It works fine. https://github.com/captnfab/PianoBooster/blob/master/tools/fluidsynth/pianobooster-fluidsynth

use_jack="1"

> For this reason I have made the dependency on JACK optional and marked this option as untested. I recommend we set this option to OFF in all the include package options.

Must be reverted.

> Removal of the dependencies on the external RTMIDI library by using the USE_SYSTEM_RTMIDI option and only use the included 3rd party source code instead.

It does not follow policy of distributions. Package must be build using system rtmidi, but for some platforms it's not possible at the moment, so we have bundled rtmidi.

> I would like the PianoBooster app about dialogue and the app help pages to point back to my site at http://pianobooster.sourceforge.net/ which I plan to update this site with more information in the future. The GitHub site https://github.com/captnfab/PianoBooster which it has been changed to is not really suitable for the end users who are not coders.

Do not need.

>  Merge the build options NO_LICENSE and NO_CHANGELOG into the NO_DOCS option.

It does not follow policy of distributions. Licence and documents install in different directories, some distributions do not install licence, but documentation.

> Change the default startup song on a fresh install from “BoosterMusic/01-ClairDeLaLune.mid” to "BeginnerCourse/01-StartWithMiddleC.mid” as beginners really need to start at the beginning.

ok

Louis, did you join to project to play games or to help with developing? Almost all your proposals are buggy, adds regress and must be rejected.

**Comment by trebmuh** [comment]
@glixx the tone you're using isn't welcoming at all. You'd better to show respect to people and talk to them even if you disagree with some of their views.

**Comment by captnfab** [comment]
I'm sorry glixx, but I disagree both with what you're saying and with the way you're saying it. You told me you were able to do team work and follow a dev leader, but obviously, you're not demonstrating that.
You're still free to contribute through PR, but I removed you from the list of collaborators since you used your privileges agains dev/project leader…

**Comment by glixx** [comment]
Good bye. You can continue to play games, but program will be forked with name QPiano and developing will be continuing by community.

**Comment by trebmuh** [comment]
@glixx : you're not wining nothing with being aggressive for free like you do here and presenting yourself as being the leader of a community which

1. existed before you, and
2. you have contributed to reduce because of the (wrong) way you communicate with other people

Have fun with programming, and I hope you'll not forget to have fun and respect with other humans, because at the end of the day, software are nothing without humans using those.

Take care.

**Comment by glixx** [comment]
I'm not agressive, but objective. Not everybody likes truth.
Fork was born because of somebody removed developer (222 commits) from project.
**Admsasha** is moving to fork from here too (137 commits). The most active developers left to fork: https://github.com/glixx/QPiano
And not authors decide what to distribute by repositories, but maintainers.
Author -> maintainer -> user.

**Comment by trebmuh** [comment]
In my opinion, you're not being objective writing the way you do. If you were, you would say/write something more like "my opinion is ... ..." and a lot less authoritative.

Some of your points could be discussed, but with the way you engage discussions with others, I bet people are thinking, like me right now, "well, it doesn't worth my time". Too bad.

Still, take care and thanks for having carried a few jobs done.

**Comment by glixx** [comment]
This is technical text, do not need to use "my opinion is ... ..."

**Comment by trebmuh** [comment]
You're free to think what you want. Maybe one day you'll reconsider.

**Comment by trebmuh** [comment]
As an example, I used to contribute (French translation) to PB. The project used to use Weblate (free software) at that time. Then captnfab didn't had anymore time to work on PB and you came in. Then, you decided to switch to Transifex (non-free software) without even without asking me if I was fine with that.

This is being authoritative. Acting like that isn't good leadership at all. It's more something called "being bossy".

Hope you'll understand this point, even if it's kind of too late now.

**Comment by glixx** [comment]
Weblate does not support many templates for free.

**Comment by trebmuh** [comment]
AFAIK, it does. It only needs communication skills to be applied when talking with the hosted.weblate people.

Even if you were right, the minimum from a project leader would be to discuss the issue with the current translators before moving from one (free software) tool to another (proprietary) one. Which you didn't.

**Comment by glixx** [comment]
At the moment PianoBooster does not have any translation platform. Transifex was switched on QPiano fork. You're welcome to work with weblate.

**Comment by trebmuh** [comment]
whatever...

**Comment by pianobooster** [comment]
Completed apart from the removal of the dependency on the external RTMIDI library.
