### ISSUE TITLE
Version 0.7.2 now ready for testing and some translations need to be updated. 

### ISSUE THREAD

**Issue by louis-barman** [pianobooster/PianoBooster#214]
Hello all version 7.2 of piano booster on the `develop` branch is nearly ready to be released.  Please checkout the `develop` branch and compile it using run `cmake .. && make` in a build directory. Please can can test it and report any new issues. However I have not tested or updated any translations and I would need some help with this task. 

If there are people who can help with translations that would be great.  Also PB seems to have a vast amount of languages with 96 translations in the repo most of them only contain a few lines of actual translations. This compares to Musescore a much more popular program that supports only 66 languages. Please can you advise what we should do about many half completed translations. 

Also Jack2 is now disabled by default as it is only really needed on BSD Unix as every thing can easily be done using Alsa MIDI connections which is the default under Linux.

**Comment by louis-barman** [comment]
I have just ran lupdate on all the translations (not on the music translations) on the develop branch.

**Comment by louis-barman** [comment]
@hanek23 Are you able to help with the Update of Czech translations on the develop branch please as I am nearly ready to do the official 0.7.2 release. Are there please any other translators who could help.

**Comment by hanek23** [comment]
Hi,
I just created a pull request for czech translations. As far as other translations I can probably translate slovak with like 95% accuracy since it is very similar to czech but I honestly do not believe to be worth it because as I said these two languages are so similar even small children have no problems understanding the other. 
edit: I just checked slovak version and it is just like 20 translations, so I will do it tomorrow.

**Comment by pianobooster** [comment]
@hanek23 Thank you so much for your contributions to the translations. I am just about to do the official release of 0.7.2. Do you have any more translations you are working on? Please let me know as soon as possible if you have finished doing the translations. If I don't hear back i'll do a release at 9 am tomorrow UK time i'll do the release anyway. Thanks again for your help.

**Comment by hanek23** [comment]
No problem. No I ran out of languages that I can personally translate. Can you please contact me on my personal email I would like to talk to you about contributing not only translations but some code as well.

**Comment by pianobooster** [comment]
@hanek23 Ok I have sent you an email. I am going ahead and release 0.7.2 now. any code contributing would have to wait until the next release.

**Comment by pianobooster** [comment]
completed
