### ISSUE TITLE
Make it possible to use system RtMidi

### ISSUE THREAD

**Issue by jnumm** [pianobooster/PianoBooster#216]
This change is planned for version 7.2:

> - Removal of the dependencies on the external RTMIDI library by using the USE_SYSTEM_RTMIDI option and only use the included 3rd party source code instead. The trouble with this is option is that doubles the support and tests when the included 3rd party source code works fine.

with the supporting goal
> - There should be as few build dependencies as possible as each added dependency makes it harder to support when the dependencies get changed and updated.

However, distros such as Debian and Fedora require that only system-provided versions of dependencies are used. Could you consider re-applying the patch to make it possible to use rtmidi as an external shared library? To reduce build options, perhaps make it the only way and remove the src/3rdparty directory?

https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code
https://fedoraproject.org/wiki/Bundled_Libraries

**Comment by trebmuh** [comment]
agreed :+1:

**Comment by pianobooster** [comment]
Do we please have anybody who would be happy to test that the external RtMidi library works correctly including testing with an external MIDI Piano keyboard. As well as the cmake builds I am also testing the qmake builds work correctly and I also want to get the Windows and MAC version working which will also need careful testing. So sorry but I really am not prepared to test this additional combination myself. There are loads of other great things i am planning for PB that I would rather spend my time on. 

@jnumm Have you tried out pianobooster with an external midi keyboard? Could you help with the testing? @trebmuh  would you be happy to test and support this option?? 

Another thought I had, is if we don't get someone to volunteer to test and support this option using an external Midi keyboard then we could just reinstated the USE_SYSTEM_RTMIDI option anyway and mark it as untested. It would probably work OK. Is that an acceptable idea? But it there was a bug in the MIDI input then that would not be very good for the end users.

Another option would be to only use the system RtMidi and drop the the built in RtMidi but then that might stop PB from being built on older systems that don't have system RT midi library available.  Also the windows and mac builds still use the built-in RtMidi and I would much rather use exactly the same build config for all three OS. Also the system RT-midi is a relatively small single source file that include code for not only Linux but also for windows and MAC and so I don't believe the code size savings would be significant if we did not link to an external library file.

Sorry I really don't want to be awkward but I really personally don't want to support two different  options myself that do exactly the same thing. But I am happy if someone else comes forward. Please let me know if you are willing to help. Or what you think is the best thing to do if we don't get any one else to support this extra option.

**Comment by pianobooster** [comment]
OK I am away at the moment and I am still considering this.

**Comment by jnumm** [comment]
Yes, I will be testing this with a Yamaha keyboard through a Roland UM-ONE USB interface later today.


Update: I tested with the changes of PR #218 on a Debian Testing system. Bundled rtmidi as well as the system-wide rtmidi (version 3.0.0) worked fine with an external MIDI keyboard. I am volunteering to keep this configuration working.

**Comment by pianobooster** [comment]
OK I think I have decided what is best is not to used `USE_SYSTEM_RTMIDI` but instead just invert the option and call it USE_BUNDLED_RTMIDI which would be disabled by default. So that the default would be to always use system rtmidi. I particularity don't want to support TWO different configurations  with cmake .. and the the distribution builds being different. In the longer term I would delete USE_BUNDLED_RTMIDI completely but for now I would rather keep that option just incase. 

@jnumm  are you ok with that suggestion. 

Also please don't forget to test `/usr/lib/qt5/bin/qmake` (i don't mind if rtmid is deteded with QMAKE

**Comment by pianobooster** [comment]
Completed
