### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ghost** [pianobooster/PianoBooster#225]
I wanted to help with the Swedish translation but it is not on Transifex anymore. Are moving translations to another platform? How can I help?

**Comment by louis-barman** [comment]
Hi @trebmuh suggested moving the all the translations to https://weblate.org/  he wrote to me "would much prefer to be using weblate like we did before since weblate is open-source." and I am fine with that as well. If everyone is happy with that then i will arrange to set it up. Also please feel free to post to this thread. http://piano-booster.2625608.n2.nabble.com/Translating-PianoBooster-td4664159.html

Please note that the booster music translation files need to be treated differently as I am planning to move the booster muisc in to there own repository. The music translations really need to be contained within the `BoosterMusicBooks.zip` zip file.

**Comment by trebmuh** [comment]
Hi @louis-barman , I'm back after having a bit out of the internet. I'm wondering if you had a go with weblate yet?

**Comment by louis-barman** [comment]
After a bit of difficulty I have just found out how to contact them about hosting this project for free as an open source project and have just sent them a request.

**Comment by trebmuh** [comment]
Nice. I hope you'll have an answer soon!

**Comment by louis-barman** [comment]
I have not heard a reply and so I have just put in a second request on this page https://hosted.weblate.org/hosting/ as follows:

**Project name**
PianoBooster

**Project website**
http://pianobooster.sourceforge.net/

**Source code repository**
https://github.com/captnfab/PianoBooster.git

**Filemask**
translations/*.ts

**Additional message**
This is my second request for you to host the PianoBooster project as I sent a previous request  on the 16 March. Please see this issue regarding the translations in the PianoBooster project. https://github.com/captnfab/PianoBooster/issues/225  

I appreciate that things are very difficult  at the moment with the Coronavirus (COVID‑19) but I would be very grateful if  you could add this open source project. 

I  am the original author and now the maintainer for the Piano Booster project.

Thank you.

**Comment by trebmuh** [comment]
Fingers crossed!

**Comment by louis-barman** [comment]
Ok Finally I checked and it now there. This is the url to use 

https://hosted.weblate.org/projects/pianobooster/pianobooster/

@jony0008 and @trebmuh please can you update the French and spanish translations.

I am not sure yet how the changes get back into the source tree. I am investigating this.

**Comment by trebmuh** [comment]
Done for the French translation. Back to 100% now.

**Comment by louis-barman** [comment]
Oh dear it should be for the `develop` branch not the `master` branch. (The same applies to your PR  #234) Please see this page https://hosted.weblate.org/projects/pianobooster/pianobooster/#information. that shows it is using the master branch.

I cannot see how to change it. @trebmuh I'll wait for your reply, before asking weblate to change it for me.

**Comment by trebmuh** [comment]
That is probably something you can change in weblate as the "pianobooster" translation owner. I can't do nothing there since I'm only a translator on weblate.

**Comment by trebmuh** [comment]
#234 closed, #235 is replacing it and targeting develop.

**Comment by pianobooster** [comment]
Support request set to weblate to change to use the `develop` branch as I cannot find a way of changing this myself and I did not see a selection of which  Repository branch to use when requesting to use weblate. 

Also @captnfab please can you change the default branch of this repo to the develop branch as I don't have access rights to do this myself.

**Comment by orangesunny** [comment]
Hi all,
I am sorry that it took me so long, all is set now, and you have admin rights there. You will also receive a short info mail soon.

Happy and libre translating!

**Comment by louis-barman** [comment]
Hi, All have now just run lupdate on the develop branch and pushed the changes it weblate. So it now ready to start translations.

(sorry @trebmuh it looks like you had simultaneously made a change in weblate while i was trying to pull the big lupdate change into  weblate and so I was forced to reset the weblate to match the captnfab repo. The good news is that I have got a copy of the changes that you made and i'll email to them to you directly)

**Comment by trebmuh** [comment]
No worries @louis-barman . See my email, this is just a 1 minute job to redo. Not a big deal. Thanks for letting me know :+1:

**Comment by orangesunny** [comment]
Hi, I hope everything is set up the right way now. Let me know if I can help with anything else 😃

**Comment by pianobooster** [comment]
Yes **finally** this has all worked correctly and so this issue can be now be closed.

**Comment by trebmuh** [comment]
:+1: thanks @pianobooster and @orangesunny
