### ISSUE TITLE
 Could not find a package configuration file provided by "Qt5LinguistTools"

### ISSUE THREAD

**Issue by vivekruhela** [pianobooster/PianoBooster#226]
I am trying to install PianoBooster in my Linux machine. But everytime, I am getting an error by giving 1st command  as `cmake . `. The error message is shoen below:
  
    PREFIX: /usr/lib/x86_64-linux-gnu/cmake/Qt5Core/Qt5CoreConfig.cmake
    DATA_DIR: share/games/pianobooster
    CMAKE_INSTALL_BINDIR: bin
    CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
    Could not find a package configuration file provided by "Qt5LinguistTools"
    with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake
    Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
    set "Qt5LinguistTools_DIR" to a directory containing one of the above
    files.  If "Qt5LinguistTools" provides a separate development package or
    SDK, be sure it has been installed.
    Call Stack (most recent call first):
     src/CMakeLists.txt:68 (FIND_PACKAGE)

     -- Configuring incomplete, errors occurred!
    See also "/mnt/g/Softwares/Music Software/PianoBooster/CMakeFiles/CMakeOutput.log".

I have checked and tried all the methods in this [thread](https://stackoverflow.com/questions/47647035/cmake-prefix-path-doesnt-help-cmake-in-finding-qt5/47647645) regarding the same error but did not get any success. Can anyone suggest how to solve this issue? Thanks

**Comment by louis-barman** [comment]
Sorry for the slow reply.

Yes it is not an easy one to find. I think you need to install `qttools5-dev`  and on my Ubuntu 19.10 it installs this file `/usr/lib/x86_64-linux-gnu/cmake/Qt5LinguistTools` that is needed. 

this is the thread that helped me find the answer https://stackoverflow.com/questions/51698075/cmake-cannot-find-qt5linguisttools-in-docker-ubuntu-18-04

Please let me know if that works for you.

**Comment by pianobooster** [comment]
I hope this problem has been fixed for you.
