### ISSUE TITLE
Assigning hands to MIDI tracks

### ISSUE THREAD

**Issue by orivej** [pianobooster/PianoBooster#228]
MIDI files exported from digital sheets often have a MIDI track per stave. For example MuseScore exports a solo piano treble hand as the first track and the bass hand as the second track. Lilypond does the same, except that its `\unfoldRepeats` produces multiple tracks per hand (e.g. 4 tracks: (1) right hand, first half of the piece, (2) left hand, first half, (3) right hand, second half, (4) left hand, second half). (See [this example](https://github.com/captnfab/PianoBooster/files/4398117/chord.zip) made with MuseScore and [midicsv](https://www.fourmilab.ch/webtools/midicsv/).)

Currently PianoBooster mixes all tracks together and guesses the note hand based on its pitch. Since hand-per-track MIDI files are readily accessible, in particular from https://musescore.com/ (after registration), it is unfortunate that PianoBooster does not handle them as expected by default.

PianoBooster could instead classify tracks (or rather subsets of tracks per the current channel) as mostly treble or mostly bass, and assign all notes from the former to the treble stave and vice versa.

Related: #69

**Comment by louis-barman** [comment]
Did you see the reply I posted to #69 ? This was the reply i posted to the original thread please see http://piano-booster.2625608.n2.nabble.com/Moving-notes-to-the-other-stave-tp7572718p7572812.html

There used to be a convention that  the left hand piano part is on MIDI channel 3 and the right hand piano part is on MIDI channel 4. 

It should be possible to change PB if there is another convention on what midi tracks are assigned to which hand. If there is please let me know which tracks are used for which hands WITH AN EXAMPLE MIDI file please. 

There trouble is that this needs to be setup on a per song bases as each MIDI file can use different midi channels for the left and right hand parts. All the music provided with PB MIDI channel 3 for the left hand and MIDI channel 4 for the right hand.

**Comment by pianobooster** [comment]
@orivej Do you please have an example midi for which _"hand-per-track MIDI files are readily accessible"_ which I can look at to see how to support this issue. I am waiting for you to respond please. I need as many examples as possible please.

**Comment by orivej** [comment]
Sorry for the delay!

The convention of using channels 3 and 4 certainly helps if one wants to prepare MIDI files for PianoBooster. However, it seems that no other software follows this convention. (For example, in order to produce such file with MuseScore I had to add another pair of piano staves, cut everything from the bass staff of the first pair and paste onto the bass staff of the second one, and assign midi channels of the two pianos in the mixer. If I then had to alter the original score, I would have to discard these changes, edit the original score, and repeat this procedure.)

I have posted [one example](https://github.com/captnfab/PianoBooster/files/4398117/chord.zip) in my first post; here is a more comprehensive one: https://github.com/captnfab/PianoBooster/files/4451026/pianobooster-examples.zip . It contains four pieces: 
1. musescore-two-hands ([source](https://musescore.com/hymns/tis-religion-that-can-give-waters-harriette-waters)) (two tracks: right hand, left hand)
2. musescore-four-hands ([source](https://musescore.com/user/20658856/scores/3991421)) (four tracks: right treble, left treble, right bass, left bass)
3. lilypond-simple (three tracks: text, right hand, left hand)
4. lilypond-unfold-repeats (five tracks: text, first half of right hand, first half of left hand, second half of right hand, second half of left hand)

It would be very useful (for me and other users) if PianoBooster could handle musescore-two-hands out of the box, without any configuration. The other three examples are more complex, and may seem too complex, however they are also less common and needed.

**Comment by louis-barman** [comment]
Ha Ha, I forgot the code I wrote all those years ago! 

You can already assign the parts to channels. just right click on the parts in the left hand window Or use the 'song/ Song details' menu. It was "hiding in plain sight".

Some one has removed the 'pb.cfg' which remembered these settings.  I will try and revert this change.

I will try a better algorithm to try and guess the left and right hand parts. maybe as follows.

1.  Check if there are two piano like instruments on channels 3 and 4.
2. Search for two   piano like instruments that are have **exactly** the same midi program (instrument) and use adjacent midi channels.  starting the search from the first channel. 
3. Try to guess which is the left and right hand channels by averaging all the note pitches on each channel a see which channel on average has the highest note. 

Is there some sort of convention for the left and right hand to Midi  Channel mapping then please let me know. If you have more publicly available examples for MIDI music that use left and right hand parts that other PB users might want to try then please let me know. Thanks.

**Comment by orivej** [comment]
Thank you!

> You can already assign the parts to channels.

Yes, this helps in the lilypond-simple case since it assigns different tracks to different channels. This does not help in musescore cases since the first piano uses the first channel, the second piano (in the four hand piece) the second; and works but is not ideal in lilypond-unfold-repeats since it splits each hand across multiple channels.

To support musescore cases, I propose to alter not the algorithm that chooses the piano channels, but the algorithm that distributes notes to hands when one channel is used for both hands. I want it to notice one of the following:

1. Exactly two tracks use the current channel
2. An even number of tracks use the current channel
3. More than one track uses the current channel

and then instead of distributing individual notes to hands, PianoBooster would distribute the whole tracks to hands:

1. Assign all notes from the first track to the right hand, and from the second to the left.
2. Assign all notes from the odd tracks to the right hand, and from the even to the left.
3. (Useful with 1 and 2 as well) Sort all tracks based on the average tone, and assign notes from the lower half of the tracks to the left hand.

EDIT: to support lilypond-unfold-repeats after supporting musescore, the only missing piece is the ability to select multiple channels for *both* hands in the channel selector.

**Comment by louis-barman** [comment]
At the moment PB does not understand the concept of SMF tracks only MIDI channels. (It decodes each midi track ok but only uses the Midi channel info at the moment). It is not impossible to change this, but it looks quite fiddly to do so, so this would have to be put on the back burner as I have other things I want to do with PB before then.  

If someone else wants to look at changing then the go ahead but PLEASE first post to the develop forum that you are working on this BEFORE you start as the change are quite fiddly.

As a quick win I could change the guess the left and right hand piano MIDI channels using my suggested  algorithm above. which would improve things for three out of four of your examples.

**Comment by louis-barman** [comment]
@orivej just to let you know this now works much better if you want to test this compile the code on the `develop` branch. If the left and right hands are assigned different midi channels then PB should now auto detect them. I think your supplied samples numbers 1 2  and 3 may now work correctly. your sample number 4 does not work yet as the left and right parts use the same midi channel. Also to be fixed is remember the manual configuration of the left and right piano parts.

**Comment by louis-barman** [comment]
@orivej  Ok this should be completely fixed now on version 0.7.4-RC1 which is in the develop branch. It was quite an involved change as the code on PB only used the MIDI channels and did not keep the MIDI file track information. It should now automatically detect the left and right hand parts as well as allow you to manually change them.

**Comment by pianobooster** [comment]
Fixed in version 0.7.4-RC1 in the develop branch.
