### ISSUE TITLE
No choices for Midi output on FreeBSD 12.1

### ISSUE THREAD

**Issue by yurivict** [pianobooster/PianoBooster#232]
The combobox only has a ```None``` choice.

FreeBSD 12.1

See also https://github.com/captnfab/PianoBooster/issues/95

**Comment by trebmuh** [comment]
@yurivict which PB version are you using?

**Comment by yurivict** [comment]
0.7.2b

**Comment by louis-barman** [comment]
I assumed you have compiled this your self? For free BSD you need to compile with the USE_JACK option turned on. Try `cmake .. -DUSE_JACK=ON`.

I suppose I could change the source code to do this automatically. So please can you try changing this line in `CMakeLists.txt` from : 
```
option(USE_JACK "build with Jack (Only required for BSD Unix)" OFF)
```
to these lines:
```
if (FreeBSD)
     option(USE_JACK "build with Jack (recommended for BSD Unix)" ON)
else()
    option(USE_JACK "build with Jack (Only required for BSD Unix)" OFF)
endif()
```

Also you need to confirm that you have `jackd` running and that it can see the `fluidsynth` which you also need to start running.

Would you be interested in becoming a PianoBooster beta tester  for FreeBSD? If so please can you post to this thread. http://piano-booster.2625608.n2.nabble.com/Helping-with-Piano-Booster-eg-testing-translators-tp7572826.html

**Comment by yurivict** [comment]
This happens on FreeBSD with ```USE_JACK=ON```.
Something is broken.

You should make this a build-time error when the list of Midi backends is empty.

**Comment by yurivict** [comment]
I tried to create a FreeBSD port, but I can't make it work myself.

**Comment by louis-barman** [comment]
Ok did you ever get a version working correctly on FreeBSD?? If you did can you let me know what version/commit that was?  and can you compare versions.

I see you raised some past issues about FreeBSD so i assumed that it was all working correctly on BSD but I will have to rely on other volunteers to test this. 

To work on the FreeBSD port you first need to get the run  `midiprobe`   In this project https://github.com/thestk/rtmidi. I get this output on Linux.

```
./midiprobe 

Compiled APIs:
  Linux ALSA
  Jack Client

Current input API: Linux ALSA

There are 2 MIDI input sources available.
  Input Port #0: Midi Through:Midi Through Port-0 14:0
  Input Port #1: Digital Keyboard:Digital Keyboard MIDI 1 24:0

Current output API: Linux ALSA

There are 4 MIDI output ports available.
  Output Port #0: Midi Through:Midi Through Port-0 14:0
  Output Port #1: Digital Keyboard:Digital Keyboard MIDI 1 24:0
  Output Port #2: Client-128:qjackctl 128:0
  Output Port #3: FLUID Synth (fs2):Synth input port (fs2:0) 130:0
```

**Comment by yurivict** [comment]
> Ok did you ever get a version working correctly on FreeBSD?? 

No.

> To work on the FreeBSD port you first need to get the run midiprobe ...

It shows no MIDI input or output devices.

After manually starting this command:
> fluidsynth -j /usr/local/share/sounds/sf2/FluidR3_GM.sf2
one MIDI output appears:
```
There are 1 MIDI output ports available.
  Output Port #0: fluidsynth-midi:midi_00
```

--------------

Some option for MIDI should work out of the box. Users won't be able to set it up if non-trivial actions are required.

The fluidsynth library allows to translate midi into sound and to register as a Jack MIDI server. You should use something like this as a default.

**Comment by yurivict** [comment]
Through the Jack interface, in case when no MIDI devices are available by default, you can instantiate the FluidSynth MIDI convertor, and connect it to the MIDI input, and the audio output, so that the system would become functional out of the box.

**Comment by louis-barman** [comment]
> After manually starting this command:
> fluidsynth -j /usr/local/share/sounds/sf2/FluidR3_GM.sf2 one MIDI output appears:

Good so if you manually start fluidsynth does it now show up in pianobooster?

Also do you have a midi piano keyboard? please connect that up and report back whether that shows up using midiprobe and pianobooster? The  midiprobe and pianobooster behaviour should be exactly the same regarding midi devices.

> Some option for MIDI should work out of the box. Users won't be able to set it up if non-trivial actions are required.

MIDI does work out of the box but you first need to connect a midi device first! I think you actually mean a midi sound generator should be started automatically for this please test the develop branch and enable the option `WITH_INTERNAL_FLUIDSYNTH` on the develop branch and report back whether this works on BSD. 

> Through the Jack interface, in case when no MIDI devices are available by default, you can instantiate the FluidSynth MIDI convertor, and connect it to the MIDI input, and the audio output, so that the system would become functional out of the box.

The Jack interface was added at your request and is not really needed on Linux with pianobooster but please test the develop branch and let me know if integrated fluid synth works for you.

**Comment by louis-barman** [comment]
@yurivict did you see my reply above? Please could you respond! Also I was just wondering whether you are involved with the BSD distributions builds? Also I was wondering if you raise this issue https://sourceforge.net/p/pianobooster/bugs/11/ which I mistakenly closed because from what I read I assumed it was working fine on BSD.

**Comment by yurivict** [comment]
> Please could you respond!

I'd retest and port a response.

> I was just wondering whether you are involved with the BSD distributions builds?

I am a port maintainer, and a FreeBSD committer. I am not involved with builds, but I can change/add ports that are built.

> I was wondering if you raise this issue https://sourceforge.net/p/pianobooster/bugs/11/

Yes

**Comment by louis-barman** [comment]
@yurivict  do you have any result from your tests? As I said _"The midiprobe and pianobooster behaviour should be exactly the same regarding midi devices."_ so if the rtmidi midiprobe works correctly then there is unlikely to be a problem with pianobooster. Can I or you close this issue now?

**Comment by louis-barman** [comment]
@yurivict "rtmidi midiprobe works correctly on BSD then there is unlikely to be a problem with pianobooster".

Closing as no response -- reopen if you still have a problem.
