### ISSUE TITLE
Unable to build with QT

### ISSUE THREAD

**Issue by cbhere** [pianobooster/PianoBooster#233]
Sorry, it might be due to my lack of expertise but I am unable to build the application using QT. Please its a humble request if someone can upload a .exe installer file so that people like me can download and install. The only available exe installer from web is for version 0.6.4 so appreciate if 0.7.2 installer can be uploaded a lot of people like me might be benefited. If it's already available please guide me.

**Comment by louis-barman** [comment]
Ha I am just about to update the website with this info. http://piano-booster.2625608.n2.nabble.com/Preview-of-NEW-PianoBooster-executable-for-Windows-amp-Linux-td7572821.html

Unless you are developer and want to contribute code. Then I recommend that you use the prebuilt binaries.

If you would help with P.B. then please see this thread http://piano-booster.2625608.n2.nabble.com/Helping-with-Piano-Booster-eg-testing-amp-translators-td7572826.html

**Comment by cbhere** [comment]
Thank you for the prompt response. I am not a developer so won't be able to support with code but I can certainly support with :
* Testing new versions and features to confirm it works correctly on your setup.
* Generally publicising PianoBooster on social media.
Thank you once again and really appreciate the time and effort put into this project.

**Comment by pianobooster** [comment]
@cbhere Does it work ok for you? In particular does the "Internal Sound (FluidSynth)" work correctly for you? Please let me know so that close this issue.

**Comment by cbhere** [comment]
Yes, FluidSynth works perfectly for me. Thank You.
