### ISSUE TITLE
Planned new release 0.7.4  -- translations and testing needed.

### ISSUE THREAD

**Issue by louis-barman** [pianobooster/PianoBooster#239]
Hello everyone. I am planning to do a new full release for Piano Booster version 0.7.3 that will include binary executable for Windows and Mac and also an AppImage for Linux users.

Please see this thread  http://piano-booster.2625608.n2.nabble.com/Preview-of-NEW-PianoBooster-executable-for-Windows-amp-Linux-td7572821.html for more info of what has changed as well as a PREVIEW of the binary builds.

To enable the new integrated fluidsynth sound generator when compiling from source you need to enable the `WITH_INTERNAL_FLUIDSYNTH` cmake option.

However we now need everyone who can to help translate all the new strings that have been added or changed since the last release.

I would especially like to thank @SantosSi @adriaaah @yurchor @sveinki @Gooyu Noke @yarons @pafri @gjdv @phrunk @glixx @admsasha @comradekingu @jony0008 @trebmuh @hanek23 @jose1711 who I think have contributed to PianoBooster translations in the past. I would be most grateful if you could update the missing translations for this new upcoming release. If you would like to contribute to the translations then either please head over to weblate. see: https://hosted.weblate.org/projects/pianobooster/pianobooster/ or alternatively please add a pull request against the **develop** branch.

Please note that the music translations do not work at the moment. These music translations **will** be used in the future but first  some code changes are needed so these translations are add to  and read from the music "BoosterMusicBooks" zip file.

**Comment by trebmuh** [comment]
@louis-barman the French GUI translation is 100% completed right now. I'll be getting soon to the "music" being 100% translated too, even if it's not yet in use, at least, it'll be ready when those _code changes_ will be done.
Have a nice release.

**Comment by trebmuh** [comment]
@louis-barman : the French GUI translation is 100% completed right now. I'll be getting soon to the "music" being 100% translated too, even if it's not yet in use. At least, it'll be ready when those code changes will be done.
Have a nice release.

_PS : it could help the translators organizing themselves if you can give a deadline for the release._

**Comment by yurchor** [comment]
@louis-barman Ukrainian translation is ready as well. Many thanks for your application.

**Comment by jose1711** [comment]
@louis-barman Slovak translation is now complete

**Comment by trebmuh** [comment]
French translation is now 100% done (GUI + music).

**Comment by louis-barman** [comment]
OK thanks to every one who has contributed to the translations. I have just pushed 0.7.4-RC1 (Release Candidate) to the develop branch if any one want to check things out before the release. I am now not planning to make any code changes just documentation changes before the release. I have increased the version number to 0.7.4 since Ubuntu added a 0.7.3-SNAPSHOT to there repository.

**Comment by trebmuh** [comment]
@louis-barman any new translation since last month?

**Comment by louis-barman** [comment]
Hi all I have just posed a new commit that updates the music tutor books which now includes translations of the tutor help pages and for this I have added a new component called **Booster Music** please see https://hosted.weblate.org/projects/pianobooster/boostermusic/

This replaces the  old **music** component  which I plan to delete shortly. However I have already copied all the existing translations into the new  **Booster Music** component.

> Please Note: the translations are now in markdown format whereas previously they where in html.

@trebmuh Please note your translation for **Skip To My Lou** contains a fragment of English text.

I would like to thank everyone who responded to this request and updated the translations.

**Comment by trebmuh** [comment]
@louis-barman thanks for spotting this fragment. I've fixed it and enjoyed this time to fix other small issues.

**Comment by comradekingu** [comment]
@louis-barman Why not just turn on sharing between components instead?
The language consistency plugin isn't on either, so I didn't know about any of the new components.

My account is https://hosted.weblate.org/user/kingu/ if you want to add me as an admin

https://hosted.weblate.org/translate/pianobooster/pianobooster/nb_NO/?checksum=9cc5157306006699 https://hosted.weblate.org/translate/pianobooster/pianobooster/nb_NO/?checksum=2f51dc2fda1bc273 https://hosted.weblate.org/translate/pianobooster/pianobooster/nb_NO/?checksum=dd41cc541209a4b0
https://hosted.weblate.org/translate/pianobooster/pianobooster/nb_NO/?checksum=9e9f8104a3d5472d https://hosted.weblate.org/translate/pianobooster/pianobooster/nb_NO/?checksum=90a966930458178d
(this one also ends in a whitespace)

all say "Midi" and not MIDI, and there is "A Bit of This Going On in Places".

https://hosted.weblate.org/translate/pianobooster/pianobooster/en/?checksum=a350a91a73ab57f1
has a doublespace in "table border"

I should have fixed this, but, well.

**Comment by louis-barman** [comment]
@comradekingu  Thanks for post and offer to help as an weblate admin which i will probably do after i have completed this next release which I am just about ready to do now. Also I probably will delay your suggested improvements and fixes until after this next release and thank you very much for pointing this out. Also I have just added Norwegian to the Booster Music which ages you requested via weblate as a new language for the now obsolete music component. There was a format change between the music component and the new booster music component and so I wrote a script to translate the html formatting to the markdown formatting.

**Comment by louis-barman** [comment]
thanks to everyone who helped with the translations.

**Comment by pafri** [comment]
Hi, I´ve just made some last refinements of both the BoosterMusic and PianoBooster localization files on Weblate. Could you include them in the release? Best regards.

**Comment by comradekingu** [comment]
@pafri Nice, did you get all the "midi"→"MIDI" and decide on "Piano Booster" vs "PianoBooster"?
I am having a bit of difficulty translating https://hosted.weblate.org/zen/pianobooster/pianobooster/nb_NO/?q=state:empty

Would be nice with some explanations or Wikipedia links, because I don't want to make mistakes or make the program unusable. Where is it "keyboard" claviature and where is it computer "keyboard"?

**Comment by pafri** [comment]
1) MIDI
2) Piano Booster: as listed in source strings; of course sometimes with flexion: "Piano Boosteru"
3) I see, there is "Piano Keyboard" in the translation file.

**Comment by louis-barman** [comment]
@pafri and @comradekingu It is too late for version 1.0.0. The current develop version is 1.0.1-SNAPSHOT. But i have just push changes for "Midi"→"MIDI" in the source code. But I have not yet decided about "Piano Booster" vs "PianoBooster".

**Comment by pafri** [comment]
Also I wish Happy Christmas to you all. :-)
