### ISSUE TITLE
missing DejaVuSans.ttf causes segfault

### ISSUE THREAD

**Issue by jose1711** [pianobooster/PianoBooster#24]
https://github.com/captnfab/PianoBooster/blob/2aa8866a6c0ecb548e12bf4b434c691b80ecbe53/src/Draw.h#L42

this line is making `DejaVuSans.ttf` in a hard-coded path a strict dependency. without this file PianoBooster segfaults

**Comment by glixx** [comment]
It's wrong way. All distros have different paths. My path is /usr/share/fonts/TTF/dejavu/DejaVuSans.ttf
So the latest git snapshot does not start.

**Comment by richardhenwood** [comment]
I also have this issue. I'm on Fedora. What OS are you using?


PS. on Fedora, I patched changed the define to "/usr/share/fonts/dejavu/DejaVuSans.ttf" and got the program to run.

**Comment by glixx** [comment]
https://pkgs.org/download//usr/share/fonts/dejavu/DejaVuSans.ttf
https://pkgs.org/download//usr/share/fonts/TTF/dejavu/DejaVuSans.ttf
https://pkgs.org/download//usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
etc.

**Comment by glixx** [comment]
Should be fixed by https://github.com/captnfab/PianoBooster/pull/30/commits/f967a7ef4db49bfd93f70d7ea55f1fade58d3261
No more dependency on font.

**Comment by jose1711** [comment]
thank you, is there a separate branch i can pull and validate?

**Comment by glixx** [comment]
https://github.com/captnfab/PianoBooster/pulls - many different fixes, just accept pull requiests.

**Comment by captnfab** [comment]
Indeed, this hardcoded dependency is wrong.
However, we need to draw a font instead of a hardcoded vectorial glyph, because notes names need translation.
There should be another way to solve this problem. Including the font would be a possibility, using system fonts could be another.
I'm not sure which is best.

The third possibility would be to hardcode glyph for translated notes… There are two main notation systems: A, B, C, D, E, F, G and Do, Ré, Mi, Fa, Sol, La, Si which have to be supported...

**Comment by glixx** [comment]
The best is do not translate notes. It solves a lot issues. If to include font Debian will delete it and will do symlink on system font with according Debian policy.

**Comment by captnfab** [comment]
I'm sorry, but I won't go for a "we don't translate note" solution. It's a required feature for many users.

**Comment by trebmuh** [comment]
I do agree with @captnfab , translated notes are a needed thing for all the non-English speaker people.

**Comment by glixx** [comment]
I did not translate notes on Russian. If to translate G -> Соль, then 4 letters instead of 1 and no place to draw it. One-letter nottation is better to read notes. No one  real notes has Russian text of notes.

**Comment by trebmuh** [comment]
You probably can open a new issue with this problem when translating the notes names in Russian.

**Comment by glixx** [comment]
No. Nobody translates notes.

**Comment by jose1711** [comment]
> No. Nobody translates notes.

that is not true. also for instance musescore translates B -> H and B♭ -> B for some languages.

**Comment by glixx** [comment]
We decided do not draw notes and improved font support: https://github.com/captnfab/PianoBooster/pull/36

**Comment by captnfab** [comment]
Fixed by fbae727a3b9e1e5aa4b3b9036f888f081d07d6c0
