### ISSUE TITLE
Allow to switch between languages within a session

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#32]
http://piano-booster.2625608.n2.nabble.com/Translating-PianoBooster-td4664159.html
**gamby** wrote: "Will this allow you to switch between language within a session or do you have to reboot or reinstall? It would be handy in the school system for our refugees.
A German translation is underway."

So needs to allow to switch between language within a session.

**Comment by trebmuh** [comment]
Adding a :+1: for this request.

**Comment by glixx** [comment]
Done by https://github.com/captnfab/PianoBooster/pull/36

**Comment by captnfab** [comment]
Thanks
