### ISSUE TITLE
Piano keyboard widget

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#38]
There is Piano keyboard widget: https://github.com/minyor/PianoBooster/commit/5ce52af374d9b3c1201294d1bd318eea305a30f6
[piano_keyboard_widget.txt](https://github.com/captnfab/PianoBooster/files/2912726/piano_keyboard_widget.txt) (patch)
![piano_keyboard_widget](https://user-images.githubusercontent.com/2681872/53531102-4c25d800-3b03-11e9-9dbe-ba29401c6ffe.png)

What do you think about adding this widget, that will be disabled by default, but can be enabled in options?

**Comment by captnfab** [comment]
I see no problem including this widget in PianoBooster. @minyor did a nice work here, and as long as it is disabled by default, it shouldn't disturb the users.

**Comment by captnfab** [comment]
Who else think it's an interesting feature to have?

**Comment by glixx** [comment]
https://github.com/captnfab/PianoBooster/pull/48

**Comment by trebmuh** [comment]
It is a very nice addition.
Well done!
