### ISSUE TITLE
Move .mid examples from debian/ branch to master

### ISSUE THREAD

**Issue by captnfab** [pianobooster/PianoBooster#4]

**Comment by captnfab** [comment]
Midi files are now present in doc/courses/*/ directories.

**Comment by captnfab** [comment]
And they can be auto-generated by running make in the music-src folder.

**Comment by trebmuh** [comment]
[This section of the README.md](https://github.com/captnfab/PianoBooster#midi-files) would be great then to be changed then.

**Comment by trebmuh** [comment]
@captnfab really closed?

**Comment by captnfab** [comment]
@trebmuh Yes, closed. The readme problem is a bug too, but it is another one :)
This bug was about midi files needing to be migrated upstream.

**Comment by trebmuh** [comment]
OK. I've opened a ticket then it doesn't get lost.
