### ISSUE TITLE
PianoBooster with JACK

### ISSUE THREAD

**Issue by richardhenwood** [pianobooster/PianoBooster#46]
I installed JACK on my Fedora laptop. I have discovered I can use PianoBooster within this environment but I need to toggle from 'None (PC Keyboard)' to the midi keyboard within 'Setup' -> 'MIDI setup' in order to get things working. Once I've switched from 'None (PC Keyboard)' I can route the MIDI signals to the app of my choice and PianoBooster also sees the signals.

I haven't had a chance to look into this more, but I thought I would share this work around now.

**Comment by glixx** [comment]
Thank you for testing.
