### ISSUE TITLE
Notes to play aren't translated

### ISSUE THREAD

**Issue by captnfab** [pianobooster/PianoBooster#5]
But translation is present in the .ts

**Comment by captnfab** [comment]
The reason is, staves are drawn in pure OpenGL with vertex coordinates. See for example https://github.com/captnfab/PianoBooster/blob/e2bb17de5bc2886b737ba2e4d75901b283a885a2/src/Draw.cpp#L135-L145

**Comment by trebmuh** [comment]
@captnfab awesome !

That said, after playing a bit with it, I don't understand why all the notes are displayed but Si# and Do (whatever if the displayed is in anglo-saxon or latin notation).

**Comment by trebmuh** [comment]
@captnfab awesome !

That said, after playing a bit with it, I don't understand why all the notes are displayed but Si# and Do (whatever if the displayed is in anglo-saxon or latin notation).

**Comment by trebmuh** [comment]
Thanks for having fixed it.
