### ISSUE TITLE
Restore wiki

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#50]
Original wiki was lost by sourceforge. Needs to restore it and write new articles.

**Comment by glixx** [comment]
Wiki pages were no cached even by google.
Author does not answer by email.
So wiki cannot be restored.

**Comment by trebmuh** [comment]
https://web.archive.org/web/20140606060338/http://sourceforge.net:80/apps/mediawiki/pianobooster/index.php?title=Main_Page
