### ISSUE TITLE
Monitor midi

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#56]
hello everyone, i´m not a developer but i would like to know if any of you developers out there would like to make pianobooster display input notes on the screen as notes instead of lines and have them moving towards the left as in playback but live from the input midi in real time? thank you

Original post: http://piano-booster.2625608.n2.nabble.com/monitor-midi-td7572729.html

**Comment by pianobooster** [comment]
Not sure what is being suggested but it seems confusing.
