### ISSUE TITLE
write and read melodies

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#59]
Hi everyone! I have an idea for pianobooster, notes played on the instrument SCROLL on the staff. I think this would be useful because it means that the melodies you can play you can automatically write them and read them and  this would become an efficient way of practising sight reading. Can someone try to make it a realoty?
Matias 

Original post: http://piano-booster.2625608.n2.nabble.com/New-feature-td7572706.html

**Comment by pianobooster** [comment]
You can already play along to any midi track.
