### ISSUE TITLE
Autoselect Fluidsynth/TiMidity as Midi Output Device

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#61]
I have a feature request: an option that automatically selects the "FLUID synth" option from the midi out device. 
Instead of always going to "setup" > "Midi setup" > "Midi out device"  and then selecting  the "FLUID synth" option from the drop down menu, it'd be great if Pianobooster could be directed to select the "FLUID synth..." option by default.

Even a cmd line option such as Pianobooster -fluidsynth=1395:0 (where 1395:0 is the current port for fluidsynth) would be helpful.

Thanks,
Preston 

Original post: http://piano-booster.2625608.n2.nabble.com/Feature-Request-Autoselect-Fluidsynth-as-Midi-Out-Device-td7572686.html

**Comment by glixx** [comment]
Same for TiMidity.

**Comment by glixx** [comment]
It must be better after fix https://github.com/captnfab/PianoBooster/issues/35
You need to select output device only once.

**Comment by glixx** [comment]
fluidsynth+jack is not good.

**Comment by pianobooster** [comment]
using the following fixes the problem.
```
fluidsynth -g 1.0 -a alsa -o midi.alsa_seq.id=fs2 /usr/share/sounds/sf2/FluidR3_GM.sf2
```
