### ISSUE TITLE
some extreme high sounds are not shown correctly

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#64]
Hello.
Bug report: If one plays in the hall of the mountin king by Gried using the program, some extreme high sounds are not shown correctly in the player. At least on Mac OSX. Some artefacts appear (basically i am speaking about few far right keys on 88 key piano).

Regards,
Mateusz Lacki 

Original post: http://piano-booster.2625608.n2.nabble.com/In-the-hall-of-mounting-king-td7572596.html

**Comment by pianobooster** [comment]
Duplicate of #87
