### ISSUE TITLE
muting one hand only

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#66]
Hello,
I recently started using pianobooster,and it's great!

But there is no way to mute the hand I am practicing while still hearing the other hand. I noticed I can mute 'parts' but both hands are on the same part. As of now, I hear both the notes I hit and the notes that the program plays, with a small delay; which is pretty confusing.
A 'mute current hand' check-box in the hands section would be greatly appreciated.

Thank you for your time!
Farfelu 

Original post: http://piano-booster.2625608.n2.nabble.com/muting-one-hand-only-td6839637.html

**Comment by pianobooster** [comment]
Please see the reply to the original post.
