### ISSUE TITLE
Moving notes to the other stave

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#69]
First, PianoBooster is a wonderful tool to practice and learn piano from MIDI files. Thanks.
Second, some notes in a musical score are placed in the other musical stave (pentagram). More precisely, high notes in the lower stave (left hand) are misplaced as low notes in the upper stave (right hand). See picture:
misplaced notes
Then, when playing only one hand (right hand) with PianoBooster, also the other hand (left hand) is needed to go on playing. This is confusing to the player. Is there a way to move those misplaced notes to the correct stave? Please, answer to  jjsalaza@ull.es   Thanks.

Original post: http://piano-booster.2625608.n2.nabble.com/Moving-notes-to-the-other-stave-td7572718.html

![nuevo](https://user-images.githubusercontent.com/2681872/58929551-29d5d300-8760-11e9-9bb9-f657188a2c3a.jpg)

**Comment by pianobooster** [comment]
Please see the reply to the original post.
