### ISSUE TITLE
Chord where left hand is arpeggio and right hand just normal chord

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#81]
Chord where left hand is arpeggio and right hand just normal chord is (by PianoBooster) expected to be played as: lowest note of left-hand + right hand full chord; then release, and then play the rest of the left hand arpeggio but should allow right hand to not be released
![59217507-62d9d180-8bbe-11e9-9637-cbe9d33a62cf](https://user-images.githubusercontent.com/2681872/59232498-4d2fd080-8bed-11e9-8ae9-4974c8c30e27.png)
arpeggio (and glissando) notes seem to be in some random order sometimes combined in chord, sometimes consecutive notes

**Comment by gjdv** [comment]
Perhaps it's an idea to try and detect arpeggio, glissando, trillers etc, and allow for more freedom (i.e., not super-strictly following the MIDI) in those cases?
Might require some research into how these effects are coded in MIDI by different composing tools.

**Comment by pianobooster** [comment]
This look correct to me PB does already try automatically try to detect arpeggios and chords and they work correctly when you try playing along.  More advanced players will not be looking at the PB screen but instead reading reading from the printed sheet music. PB does not work that well with very advanced pieces of music -- but if you are already an advanced player then you won't be using PB.
