### ISSUE TITLE
Two hand arpeggio chord

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#82]
Two hand arpeggio chord is expected (by PianoBooster) to be played as: 2-hand simultaneous, while should be played as single sequence from left to right.
![59217735-ea274500-8bbe-11e9-98c4-2227bef3f9b9](https://user-images.githubusercontent.com/2681872/59232522-6cc6f900-8bed-11e9-9285-08afe149fe5a.png)
arpeggio (and glissando) notes seem to be in some random order sometimes combined in chord, sometimes consecutive notes

**Comment by pianobooster** [comment]
The MIDI file needs to be edited. so that the left hand notes are on channel 4 and right hand notes are one channel 3. Also PB is aimed at beginners and two hand arpeggio are really for advanced users
