### ISSUE TITLE
Glissando shows up as 4 blocks of successive notes

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#83]
Glissando shows up as 4 blocks of successive notes that are expected to be pressed same time rather than sequential:
![59217837-23f84b80-8bbf-11e9-87b8-d537edaf29d2](https://user-images.githubusercontent.com/2681872/59232651-f8d92080-8bed-11e9-8335-1592b00c89b6.png)
arpeggio (and glissando) notes seem to be in some random order sometimes combined in chord, sometimes consecutive notes

**Comment by pianobooster** [comment]
This is an imperfection of trying to interpret the score from midi data as all notes in a cord may not be played at exactly the same time with some notes in a cord being played before other notes. However if you have a printed musical score for this piece then I believe that you will still be able to play along to this.
