### ISSUE TITLE
-lGL is missing, the link fails with undefined OpenGL symbols

### ISSUE THREAD

**Issue by yurivict** [pianobooster/PianoBooster#94]

**Comment by glixx** [comment]
Where did you add it?

**Comment by yurivict** [comment]
I added it to LDFLAGS, but it should be added in cmake files as a library needed for the executable.

**Comment by glixx** [comment]
I guess you need to add in CMakeLists.txt:
```IF(${CMAKE_SYSTEM} MATCHES "FreeBSD")```
like Linux:
```
IF(${CMAKE_SYSTEM} MATCHES "Linux")
        ADD_DEFINITIONS(-D__LINUX_ALSASEQ__)
        LINK_LIBRARIES (asound)
        LINK_LIBRARIES (pthread)
        LINK_LIBRARIES (GL)
ENDIF(${CMAKE_SYSTEM} MATCHES "Linux")
```
Because we do not have definitions for FreeBSD even jack was not linked: https://github.com/captnfab/PianoBooster/issues/95

**Comment by glixx** [comment]
Should be fixed.
