### ISSUE TITLE
Jack in Linux

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#96]
Mageia Linux.
cmake with -DUSE_SYSTEM_RTMIDI=ON enables Jack.
pianobooster sees jack, but no sound.
![Снимок экрана от 2019-06-12 07-28-26](https://user-images.githubusercontent.com/2681872/59323594-f6f18900-8ce3-11e9-87f3-c54dbfc4f079.png)

**Comment by hpladds** [comment]
PianoBooster - Version 0.7.0 
Ubuntu 18.04
AMD 64

No options offered to setup either midi input or output.

The keyboard plays notes using Fluidsynth and Jackd:
$ fluidsynth --server --audio-driver=jack --connect-jack-outputs /usr/share/sounds/sf2/FluidR3_GM.sf2
$ aconnect -i && aconnect -o

> client 0: 'System' [type=kernel]
>     0 'Timer           '
>     1 'Announce        '
> client 14: 'Midi Through' [type=kernel]
>     0 'Midi Through Port-0'
> client 24: 'Keystation 49es' [type=kernel,card=2]
>     0 'Keystation 49es MIDI 1'
>     1 'Keystation 49es MIDI 2'
> client 14: 'Midi Through' [type=kernel]
>     0 'Midi Through Port-0'
> client 24: 'Keystation 49es' [type=kernel,card=2]
>     0 'Keystation 49es MIDI 1'
> client 130: 'FLUID Synth (17232)' [type=user,pid=17232]
>     0 'Synth input port (17232:0)'

$ aconnect 24:0 130:0

$ pianobooster | more

> ERROR: Cannot find BoosterMusicBooks.zip
> QFileInfo::absolutePath: Constructed with empty filename
> QFileInfo::absolutePath: Constructed with empty filename
> QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
> Trace: resourceDir1 /usr/local/bin/../music/
> Trace: resourceDir2 /usr/local/bin/../../music/
> Info: applicationDirPath=/usr/local/bin
> Trace: resourceDir3 /usr/local/bin/../share/games/pianobooster/music/
> Trace: xx /usr/local/bin/../share/games/pianobooster/music/BoosterMusicBooks.zip
> Info: Tracks 5 PPQN 192
> Dbug: Track 0 length    83: Track Length 83
> Dbug: Track 0 length    26: Key Signature 4/4 metronome 48 quarter 8
> Dbug: Track 0 length    11: Seq/Track Name Up And Down
> Dbug: Track 1 length    21: Track Length 21
> Dbug: Track 1 length     8: Seq/Track Name Solo-Left
> Dbug: Track 2 length   330: Track Length 330
> Dbug: Track 2 length   316: Seq/Track Name Solo-Right
> Dbug: Track 3 length   415: Track Length 415
> Dbug: Track 3 length   407: Seq/Track Name Drum
> Dbug: Track 4 length  1021: Track Length 1021
> Dbug: Track 4 length  1002: Seq/Track Name Plectrum-Guitar
> Time    0 chan  0 type MIDI_PB_timeSignature note   4 velocity   4 deltaTime   0
> Time    0 chan  2 type MIDI_PROGRAM_CHANGE  note   0 velocity   0 deltaTime 768
> Time    0 chan  3 type MIDI_PROGRAM_CHANGE  note   0 velocity   0 deltaTime 768
> Time    0 chan  9 type MIDI_PROGRAM_CHANGE  note   0 velocity   0 deltaTime   0
> Time    0 chan 15 type MIDI_PROGRAM_CHANGE  note  24 velocity   0 deltaTime 768

![PianoBooster](https://user-images.githubusercontent.com/7605734/60112531-f6261180-973d-11e9-8162-5823606fe411.jpg)

**Comment by glixx** [comment]
@hpladds your installation is incorrect. It should be installed in /usr instead of /usr/local.
Try Ubuntu package instead https://software.opensuse.org/download.html?project=home%3Aloginov_alex_valer&package=pianobooster

**Comment by glixx** [comment]
There is testing fluidsynth with jack: https://github.com/captnfab/PianoBooster/issues/142

**Comment by glixx** [comment]
It works ok in Mageia and Ubuntu at the moment. Testing: https://github.com/captnfab/PianoBooster/issues/142
